### ISSUE TITLE
Menu appears in oversized height

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/cinnamon#10237]
```
 * Cinnamon version 5.0.5
   - No PPA's in use.
 * Distribution - Mint 20.2
 * Graphics hardware: GeForce GTX 970, driver used: NVIDIA 460.91.03
 * 64 bit

**Issue**
Since version 20.2, the menu sometimes expands greatly in height. I need to restart Cinnmon to fix the problem. 
I don't see any previous action logically related to this. I do not have any PPA's or extensions running. 
It would be great if this bug would be fixed soon. If you need any more information, please let me know. 


**Steps to reproduce**
While I have some programs open (e.g. Nemo, Xed) the menu sometimes appears in oversized height. 
Only a restart of Cinnamon fixes the problem. 

```
![Menü_groß](https://user-images.githubusercontent.com/51761218/126945381-f5c26848-54fb-498e-b183-8f1e6fc8552d.jpg)

**Comment by JosephMcc** [comment]
This seems to be triggered by anything that changes in the menu. Such as adding/removing an application or anything else that adds or removes an entry.

**Comment by jakoblm** [comment]
The only thing I've done here is type an application into the menu search. I hope that this bug can be easily fixed?

**Comment by icarter09** [comment]
This has been fixed. 

https://github.com/linuxmint/cinnamon/commit/62507a53541b40f7fd2502fa97e27dea68aff538

**Comment by jakoblm** [comment]
Okay, thanks. When will the fix be distributed via update? The bug is still present in LM 20.2 and LMDE 4.
