### ISSUE TITLE
Smart hide panel problem

### ISSUE THREAD

**Issue by daddy33** [linuxmint/cinnamon#10849]
Cinnamon version - 5.4.0-2
 * Distribution - Garuda Linux (arch)
 * Graphics hardware *and* driver used - gt 1030, nvidia proprietary 515.48.07-2
 * 64 bit

Hello,

the panel smart hide feature seems to cause Cinnamon crash in 5.4:

 JS ERROR: Error: No signal 'switch-workspace-complete' on object 'CinnamonWM'

**Comment by JosephMcc** [comment]
Please edit your issue to include the filled out issue template. It's there for a reason and provides pertinent information.

**Comment by pkap575** [comment]
I am also having the same issue of crashing to blank screen after the update except the intelligently hide panel feature is disabled on my system.

Cinnamon version - 5.4.0-2
Distribution - Garuda Linux (arch)
Graphics hardware and driver used - GTX 960M, nvidia proprietary 515.48.07
64 bit

**Comment by warwickmm** [comment]
Same problem here.

```
 * Cinnamon version (cinnamon --version): Cinnamon 5.4.0
 * Distribution: Arch
 * Graphics hardware *and* driver used:
 
 00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
	Subsystem: Lenovo Device 225c
	Flags: bus master, fast devsel, latency 0, IRQ 138
	Memory at 2ffa000000 (64-bit, non-prefetchable) [size=16M]
	Memory at b0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at e000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915

 * 32 or 64 bit: 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog:

 discover_other_daemon: 1discover_other_daemon: 1discover_other_daemon: 1[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
[cinnamon-settings-daemon-smartcard] Failed to start: no suitable smartcard driver could be found
mutter-Message: 13:16:43.090: Enabling experimental feature 'x11-randr-fractional-scaling'
Gjs-Message: 13:16:43.839: JS LOG: About to start Cinnamon
Gjs-Message: 13:16:43.862: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 20 ms
Gjs-Message: 13:16:43.865: JS LOG: [LookingGlass/info] loading user theme: /home/ken/.themes/Mint-Y-Dark/cinnamon/cinnamon.css
Gjs-Message: 13:16:43.883: JS LOG: [LookingGlass/info] added icon directory: /home/ken/.themes/Mint-Y-Dark/cinnamon

(cinnamon:14523): Gjs-CRITICAL **: 13:16:43.931: JS ERROR: Error: No signal 'switch-workspace-complete' on object 'CinnamonWM'
_connect@/usr/share/cinnamon/js/misc/signalManager.js:130:36
connect@/usr/share/cinnamon/js/misc/signalManager.js:137:14
_processPanelAutoHide@/usr/share/cinnamon/js/ui/panel.js:2673:33
_init@/usr/share/cinnamon/js/ui/panel.js:2084:14
Panel@/usr/share/cinnamon/js/ui/panel.js:2013:10
_loadPanel@/usr/share/cinnamon/js/ui/panel.js:846:25
_fullPanelLoad@/usr/share/cinnamon/js/ui/panel.js:486:26
_init@/usr/share/cinnamon/js/ui/panel.js:376:14
PanelManager@/usr/share/cinnamon/js/ui/panel.js:361:10
start@/usr/share/cinnamon/js/ui/main.js:416:20
@<main>:1:47

** Message: 13:16:43.931: Execution of main.js threw exception: Script <main> threw an exception
conky: desktop window (79b) is root window
conky: window type - dock
conky: drawing to created window (0x2a00002)
conky: drawing to double buffer

** (nemo-desktop:14559): WARNING **: 13:16:44.314: Current gtk theme is not known to have nemo support (Adwaita-dark) - checking...

** (nemo-desktop:14559): WARNING **: 13:16:44.414: The theme appears to have no nemo support.  Adding some...
** Message: 13:16:44.423: nemo-desktop: session is cinnamon, establishing proxy
blueman-applet 13.16.44 WARNING  PluginManager:147 __load_plugin: Not loading DhcpClient because its conflict has higher priority
blueman-applet 13.16.44 WARNING  PluginManager:147 __load_plugin: Not loading PPPSupport because its conflict has higher priority
cinnamon-session[14409]: WARNING: t+3.24567s: Detected that screensaver has appeared on the bus

** (nemo-desktop:14559): WARNING **: 13:16:49.283: nemo-desktop: Desktop failsafe timeout reached, applying fallback behavior

(xapp-sn-watcher:14555): GLib-GObject-CRITICAL **: 13:17:14.176: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(xapp-sn-watcher:14555): GLib-GIO-CRITICAL **: 13:17:14.177: g_dbus_interface_skeleton_flush: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(xapp-sn-watcher:14555): GLib-GObject-CRITICAL **: 13:17:14.177: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(xapp-sn-watcher:14555): GLib-GIO-CRITICAL **: 13:17:14.177: g_dbus_interface_skeleton_flush: assertion 'G_IS_DBUS_INTERFACE_SKELETON (interface_)' failed

(xapp-sn-watcher:14555): GLib-GObject-WARNING **: 13:17:14.177: invalid (NULL) pointer instance

(xapp-sn-watcher:14555): GLib-GObject-CRITICAL **: 13:17:14.177: g_signal_emit_by_name: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
cinnamon-session[14409]: WARNING: t+33.25377s: Detected that screensaver has left the bus
conky: X Error: Display 55e56bdb2240
 ```

**Issue**

If the panel is set to always show or intelligently hide, then after logging in Cinnamon crashes.  No windows are displayed, no panels are displayed, the main menu is not displayed, etc.


**Steps to reproduce**

Enable "Intelligently hide panel", log out, and then log back in.  Enabling "Always show panel", avoids the problem.


**Expected behaviour**

No errors after starting session.



**Other information**

**Comment by mtwebster** [comment]
Fixed by https://github.com/linuxmint/cinnamon/commit/9633212b2a3556dc9ac95ab537f1a6de9b20e5d3

**Comment by daddy33** [comment]
The new package in arch repos (5.4.1-1) fixes the cinnamon crashing issue. But the smart hide feature still does not seem to work properly. If I maximize a nemo window, the panel overlaps it.  I have to drag my mouse cursor to the bottom to make the panel hide. Then if I resize the window, the panel remains hidden. For the programs that start maximized, the panel hides as it should, but then I can't make the panel pop-up by dragging down the mouse cursor, it just makes the panel "blink".

**Comment by warwickmm** [comment]
@daddy33, I created new issues for these: #10869, #10870
