### ISSUE TITLE
The wallpaper disappeared with version 5.4.0

### ISSUE THREAD

**Issue by Bundy01** [linuxmint/cinnamon#10852]
```
 * Cinnamon version (cinnamon 5.4.0)
 * Distribution - (Arch)
 * Graphics hardware *and* driver used: Intel CometLake-U GT2 [UHD Graphics] - i915
 * 64 bit
 * cinnamon -r
mutter-Message: 00:40:08.200: Enabling experimental feature 'x11-randr-fractional-scaling'
Gjs-Message: 00:40:08.599: JS LOG: About to start Cinnamon
Gjs-Message: 00:40:08.621: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 20 ms
Gjs-Message: 00:40:08.623: JS LOG: [LookingGlass/info] loading user theme: ~/.themes/CBlue/cinnamon/cinnamon.css
Gjs-Message: 00:40:08.634: JS LOG: [LookingGlass/info] added icon directory: ~/.themes/CBlue/cinnamon
Gjs-Message: 00:40:08.792: JS LOG: [LookingGlass/info] loaded at Sun Jun 19 2022 00:40:08 GMT+0200 (heure d’été d’Europe centrale)
Gjs-Message: 00:40:08.793: JS LOG: Cinnamon started at Sun Jun 19 2022 00:40:08 GMT+0200 (heure d’été d’Europe centrale)
Gjs-Message: 00:40:08.793: JS LOG: GPU offload supported: false
Gjs-Message: 00:40:08.797: JS LOG: [LookingGlass/info] ExtensionSystem started in 0 ms
Gjs-Message: 00:40:08.797: JS LOG: [LookingGlass/info] DeskletManager started in 0 ms
Gjs-Message: 00:40:08.798: JS LOG: [LookingGlass/info] SearchProviderManager started in 0 ms
Gjs-Message: 00:40:08.909: JS LOG: [LookingGlass/info] Loaded applet show-desktop@cinnamon.org in 72 ms
Gjs-Message: 00:40:08.912: JS LOG: [LookingGlass/info] Role locked: tray
Gjs-Message: 00:40:08.915: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 6 ms
Gjs-Message: 00:40:08.922: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 6 ms
Gjs-Message: 00:40:08.935: JS LOG: [LookingGlass/info] Loaded applet user@cinnamon.org in 13 ms
Gjs-Message: 00:40:08.945: JS LOG: [LookingGlass/info] Loaded applet recent@cinnamon.org in 10 ms
Gjs-Message: 00:40:08.949: JS LOG: [LookingGlass/info] Loaded applet on-screen-keyboard@cinnamon.org in 4 ms
Gjs-Message: 00:40:09.045: JS LOG: [LookingGlass/info] [weather@mockturtl#48]: Internet access now available, resuming operations.
Gjs-Message: 00:40:09.055: JS LOG: [LookingGlass/info] Loaded applet weather@mockturtl in 106 ms
Gjs-Message: 00:40:09.118: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 00:40:09.124: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 68 ms
Gjs-Message: 00:40:09.135: JS LOG: [LookingGlass/info] Loaded applet spices-notifier@germanfr in 11 ms
Gjs-Message: 00:40:09.158: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 23 ms
Gjs-Message: 00:40:09.163: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 5 ms

(cinnamon:12377): Clutter-WARNING **: 00:40:09.235: Attempting to add actor of type 'StBin' to a container of type 'CinnamonGenericContainer', but the actor has already a parent of type 'CinnamonGenericContainer'.
Gjs-Message: 00:40:09.238: JS LOG: [LookingGlass/info] Loaded applet smallcalc_applet@lerc.sds in 75 ms
Gjs-Message: 00:40:09.246: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 8 ms
Gjs-Message: 00:40:09.249: JS LOG: [LookingGlass/warning] Failed to add launcher from path: org.gnome.Terminal.desktop
Gjs-Message: 00:40:09.266: JS LOG: [LookingGlass/info] Role locked: panellauncher
Gjs-Message: 00:40:09.269: JS LOG: [LookingGlass/info] Loaded applet panel-launchers@cinnamon.org in 23 ms
Gjs-Message: 00:40:09.294: JS LOG: [LookingGlass/info] Loaded applet batterymonitor@pdcurtis in 25 ms
Gjs-Message: 00:40:09.297: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 00:40:09.321: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 27 ms

(cinnamon:12377): Gjs-WARNING **: 00:40:09.389: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 _get_timezone() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":123:21]
1 ActivityLogging() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":95:62]
2 vpnLookOut() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":231:31]
3 main() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":1385:11]
4 createApplet() ["/usr/share/cinnamon/js/ui/appletManager.js":598:24]
5 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":373:33]
6 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":102:13]
7 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":274:31]


(cinnamon:12377): Gjs-WARNING **: 00:40:09.434: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 get_vpn_names() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":651:31]
1 makeMenu() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":984:41]
2 vpnLookOut() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":441:17]
3 main() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":1385:11]
4 createApplet() ["/usr/share/cinnamon/js/ui/appletManager.js":598:24]
5 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":373:33]
6 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":102:13]
7 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":274:31]


(cinnamon:12377): Gjs-WARNING **: 00:40:09.439: Some code called array.toString() on a Uint8Array instance. Previously this would have interpreted the bytes of the array as a string, but that is nonstandard. In the future this will return the bytes as comma-separated digits. For the time being, the old behavior has been preserved, but please fix your code anyway to explicitly call ByteArray.toString(array).
(Note that array.toString() may have been called implicitly.)
0 toString() ["self-hosted":544:0]
1 updateUI() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":1161:71]
2 updateLoop() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":1339:17]
3 on_settings_changed() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":712:13]
4 vpnLookOut() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":484:17]
5 main() ["/usr/share/cinnamon/js/misc/fileUtils.js line 211 > Function":1385:11]
6 createApplet() ["/usr/share/cinnamon/js/ui/appletManager.js":598:24]
7 addAppletToPanels() ["/usr/share/cinnamon/js/ui/appletManager.js":373:33]
8 finishExtensionLoad() ["/usr/share/cinnamon/js/ui/appletManager.js":102:13]
9 _init/<() ["/usr/share/cinnamon/js/ui/extension.js":274:31]

Gjs-Message: 00:40:09.450: JS LOG: [LookingGlass/info] Loaded applet vpnLookOut@claudiux in 129 ms
wgnord: 10587388   12624    0    0    0     0          0         0  2014922    8913    0    0    0     0       0          0
Gjs-Message: 00:40:09.472: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 22 ms
Gjs-Message: 00:40:09.503: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 31 ms
Gjs-Message: 00:40:09.660: JS LOG: [LookingGlass/info] Loaded applet CinnVIIStarkMenu@NikoKrause in 157 ms
Gjs-Message: 00:40:09.661: JS LOG: [LookingGlass/info] AppletManager started in 868 ms
Gjs-Message: 00:40:09.671: JS LOG: Unknown network device type, is 14
Gjs-Message: 00:40:09.677: JS LOG: Unknown network device type, is 30
Gjs-Message: 00:40:09.677: JS LOG: Unknown network device type, is 29
Gjs-Message: 00:40:09.691: JS LOG: [LookingGlass/info] Adding systray: keepassxc (22x22px)
Gjs-Message: 00:40:09.702: JS LOG: [LookingGlass/info] Adding systray: tuxedo-control-center1 (16x16px)
Gjs-Message: 00:40:09.704: JS LOG: [LookingGlass/info] Adding systray: blueman (16x16px)
Gjs-Message: 00:40:09.705: JS LOG: [LookingGlass/info] Adding systray: mailspring1 (16x16px)
Gjs-Message: 00:40:09.707: JS LOG: [LookingGlass/info] Hiding systray: network
Window manager warning: vpnLookOut@claudiux - Overwriting existing binding of keysym 76 with keysym 76 (keycode 37).
Gjs-Message: 00:40:10.710: JS LOG: [LookingGlass/info] [weather@mockturtl#48]: Weather Information refreshed
 ```

**Issue**
When I start up, I have a black screen (with mouse pointer) after lightdm. I have the Cinnamon startup sound, but nothing happens afterwards.
To use the system, I use the shortcut Ctrl+Alt+escap. With that, I have the panel, plank... But the background still doesn't appear.

https://pix.milkywan.fr/qUPJEubi.png

**Steps to reproduce**
Install new version 5.4.0

**Comment by Bundy01** [comment]
journalctl -b|grep -i cinnamon:
https://0x0.st/ouYg.txt

**Comment by hsbasu** [comment]
I am also experiencing the same. In my case cinnamon built from latest commit on Ubuntu Jammy, cinnamon-session is not running properly. Manually starting muffin seems to restore the wallpaper and window decoration but the panel does not appear.

**Comment by JosephMcc** [comment]
@hsbasu That's because when you start only muffin you are not running Cinnamon. You are running muffin with it's inbuilt default plugin which really doesn't do very much.

**Comment by hsbasu** [comment]
@JosephMcc After running muffin I tried the command `cinnamon --replace`. But it ended with a crash.

**Comment by hsbasu** [comment]
The problem was resolved after I ran `cinnamon-launcher` instead of `cinnamon --replace`

**Comment by Bundy01** [comment]
@hsbasu The problem is not solved for me with the described commands.

**Comment by hsbasu** [comment]
> @hsbasu The problem is not solved for me with the described commands.

In my case as well, this solution worked on one system. On another it did not work. Try running `muffin` from terminal. As @JosephMcc suggested, if the problem is with the window manager, i.e. muffin in this case, then you should at least get the wallpaper.

**Comment by Bundy01** [comment]
@hsbasu With the command `muffin -r`, the wallpaper appears well but I have no panel :/

**Comment by hsbasu** [comment]
I don't know what's causing this, but what worked for me is with muffin running i first reset my display setting and then ran `cinnamon-launcher`

**Comment by Bundy01** [comment]
Problem solved by version 5.4.1 of cinnamon and muffin :) .
