### ISSUE TITLE
fractional scaling not working when setting on individual monitors

### ISSUE THREAD

**Issue by astromatt42** [linuxmint/cinnamon#11189]
I am using a docking station connected to two external displays with a HiDPI laptop screen. Getting fractional scaling to work was a bit of hit and miss in LM 20, however it has now broken again in 21.
The setting should be 100% for the two external monitors and 200% for the laptop screen. When I do this, the layout seems to be correct, see screenshot one, however it forces the external monitors to overflow badly, i.e. I am only shown the top left quadrant blown up by a factor of 2 on each external monitor, while the laptop screen scales correctly.
If I set everything to 100% (Screenshot 2), the external monitors are set correctly, however the laptop screen is now unscaled so too small (as expected).
I have tried this with the Nvidia and the nouveau open source drivers, the behaviour is the same.

Cinnamon 5.4.12
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/9639831/xsession-errors.txt)
![Screenshot_1](https://user-images.githubusercontent.com/52516083/192124180-906b675b-aaf5-4106-a862-820cd5418309.png)
![Screenshot_2](https://user-images.githubusercontent.com/52516083/192124181-2ae4fb5e-a708-41ad-98cd-a4f3fa7d656d.png)

**Comment by astromatt42** [comment]
A workaround for this is to manually force a lower resolution on the HiDPI monitor when connected to the docking station, however the fractional scaling should still work.

**Comment by ridiche34** [comment]
Same problem, pls fix.
@astromatt42, can you please elaborate, I don't understand.

**Comment by astromatt42** [comment]
Hi, I'm closing this as it has been resolved since with updates. It was a problem of not being able to independently scale screens.

**Comment by ridiche34** [comment]
I am still experiencing this exact issue on the edge variant of 21.3 Cinnamon.

Upon scaling any monitor by a fractional value ("Enable fractional scaling controls (experimental)"), my second monitor only shows the top right corner of what it's supposed to show (my laptop monitor works perfectly fine).

**Comment by astromatt42** [comment]
Ok, I leave it open if you're still having issues. I don't remember when it resolved itself and am currently in the field so don't have an opportunity to test it with my setup for at least another few weeks.

**Comment by RemiDav** [comment]
This issue seems to be happening when 2 GPUs are used (AMD+Nvidia).
See another case: https://forums.linuxmint.com/viewtopic.php?t=404395

I have the same issue on my laptop: if I try to scale one screen, the second one overflows on the external monitor and I only see a quarter of it. This is an issue as it makes the main screen unreadable with tiny text and buttons.

```System:
  Kernel: 6.14.0-37-generic arch: x86_64 bits: 64 compiler: gcc v: 13.3.0 clocksource: tsc
  Desktop: Cinnamon v: 6.4.8 tk: GTK v: 3.24.41 wm: Muffin v: 6.4.1 vt: 7 dm: LightDM v: 1.30.0
    Distro: Linux Mint 22.2 Zara base: Ubuntu 24.04 noble

CPU:
  Info: 16-core model: AMD Ryzen 9 7945HX with Radeon Graphics bits: 64 type: MT MCP MCM
    smt: enabled arch: Zen 4 rev: 2 cache: L1: 1024 KiB L2: 16 MiB L3: 64 MiB
  Speed (MHz): avg: 2100 high: 2475 min/max: 400/2501 boost: disabled cores: 1: 2475 2: 2475
    3: 2473 4: 2473 5: 1480 6: 2474 7: 2472 8: 2474 9: 1480 10: 2475 11: 2467 12: 2475 13: 1480
    14: 1480 15: 2461 16: 1480 17: 2472 18: 1480 19: 2474 20: 2475 21: 2475 22: 2475 23: 2475
    24: 2475 25: 2470 26: 2474 27: 1480 28: 1480 29: 1480 30: 1480 31: 1480 32: 1480
    bogomips: 159698
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: NVIDIA AD104M [GeForce RTX 4080 Max-Q / Mobile] vendor: ASUSTeK driver: nvidia
    v: 580.95.05 arch: Lovelace pcie: speed: 5 GT/s lanes: 8 ports: active: none off: DP-1
    empty: DP-2,HDMI-A-1,eDP-1 bus-ID: 01:00.0 chip-ID: 10de:27a0 class-ID: 0300
  Device-2: AMD Raphael vendor: ASUSTeK driver: amdgpu v: kernel arch: RDNA-2 pcie:
    speed: 16 GT/s lanes: 16 ports: active: DP-5,eDP-2 empty: DP-3,DP-4,Writeback-1 bus-ID: 09:00.0
    chip-ID: 1002:164e class-ID: 0300 temp: 66.0 C
  Device-3: Sonix USB2.0 FHD UVC WebCam driver: uvcvideo type: USB rev: 2.0 speed: 480 Mb/s
    lanes: 1 bus-ID: 7-1:2 chip-ID: 3277:0018 class-ID: 0e02
  Display: x11 server: X.Org v: 21.1.11 with: Xwayland v: 23.2.6 driver: X: loaded: amdgpu,nvidia
    unloaded: fbdev,modesetting,nouveau,vesa dri: radeonsi
    gpu: amdgpu,nv_platform,nvidia,nvidia-nvswitch display-ID: :0 screens: 1
  Screen-1: 0 s-res: 5560x3020 s-dpi: 96 s-size: 1471x799mm (57.91x31.46")
    s-diag: 1674mm (65.91")
  Monitor-1: DP-1-0 pos: 1-1 res: 1080x1920 hz: 60 dpi: 158 size: 174x293mm (6.85x11.54")
    diag: 341mm (13.42") modes: N/A
  Monitor-2: DisplayPort-4 pos: 4-2 res: 3840x1100 hz: 60 dpi: 287 size: 340x100mm (13.39x3.94")
    diag: 354mm (13.95") modes: N/A
  Monitor-3: HDMI-1-0 pos: 3-3 res: 1920x1080 hz: 60 dpi: 166 size: 293x174mm (11.54x6.85")
    diag: 341mm (13.42") modes: N/A
  Monitor-4: eDP-1 pos: primary,2-2 res: 2560x1600 hz: 240 dpi: 188 size: 345x215mm (13.58x8.46")
    diag: 407mm (16") modes: N/A
  API: EGL v: 1.5 hw: drv: nvidia nouveau drv: nvidia drv: amd radeonsi platforms: device: 0
    drv: nvidia device: 1 drv: radeonsi device: 2 drv: nouveau device: 3 drv: swrast gbm:
    drv: kms_swrast surfaceless: drv: nvidia x11: drv: radeonsi inactive: wayland
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: amd mesa v: 25.0.7-0ubuntu0.24.04.2 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon 610M (radeonsi raphael_mendocino LLVM 20.1.2 DRM 3.61
    6.14.0-37-generic) device-ID: 1002:164e

```
