### ISSUE TITLE
Text-Shadow in Theme Causes Segmentation Fault

### ISSUE THREAD

**Issue by vlad0337187** [linuxmint/cinnamon#12712]
### Distribution

Mint 22.1

### Package version

6.4.6

### Graphics hardware in use

Nvidia Gefore GT 1050

### Frequency

Always

### Bug description

If to specify "text-shadow" property in "#menu-search-entry" or ".menu" of "cinnamon.css" - it'll cause crash on main menu open.

<details>
<summary>Code causing problems:</summary>

```css
#menu-search-entry {
  text-shadow: -1px 1px 3px rgba(255, 255, 255, 0.5);
}

.menu {
  text-shadow: -1px 1px 3px rgba(0, 0, 0, 1);
}
```

</details>

<details>
<summary>Example /usr/share/cinnamon/theme/cinnamon.css causing crash:</summary>

[cinnamon.css.zip](https://github.com/user-attachments/files/18649326/cinnamon.css.zip)

(added 2 first blocks)

</details>

### Steps to reproduce

- have latest Linux Mint 22.1 with Cinnamon 6.4.6
- copy provided cinnamon.css to /usr/share/cinnamon/theme/cinnamon.css or modify it accordingly
- reload theme
- open main menu

### Expected behavior

No crashes, "text-shadow" is applied.

### Additional information

<details>
<summary>Logs</summary>

```sh
vlad@HP:~$ cinnamon --replace
Gjs-Message: 15:53:49.723: Profiler is disabled. Not setting up signals.
Gjs-Message: 15:53:50.327: JS LOG: About to start Cinnamon (X11 backend)
Gjs-Message: 15:53:50.457: JS LOG: [LookingGlass/info] Cinnamon.AppSystem.get_default() started in 0 ms
Gjs-Message: 15:53:50.464: JS LOG: [LookingGlass/info] loading user theme: /home/vlad/.themes/Glass-Mint-Classic/cinnamon/cinnamon.css
Gjs-Message: 15:53:50.545: JS LOG: [LookingGlass/info] added icon directory: /home/vlad/.themes/Glass-Mint-Classic/cinnamon
Gjs-Message: 15:53:50.964: JS LOG: [LookingGlass/info] NetworkManager agent: enabled
Gjs-Message: 15:53:50.978: JS LOG: [LookingGlass/info] Polkit agent: enabled
Gjs-Message: 15:53:50.979: JS LOG: [LookingGlass/info] SSH agent: enabled
Gjs-Message: 15:53:51.000: JS LOG: [LookingGlass/info] loaded at Sun Feb 02 2025 15:53:50 GMT+0000 (Coordinated Universal Time)
Gjs-Message: 15:53:51.000: JS LOG: Cinnamon started at Sun Feb 02 2025 15:53:50 GMT+0000 (Coordinated Universal Time)
Gjs-Message: 15:53:51.040: JS LOG: [LookingGlass/info] ExtensionSystem started in 3 ms
Gjs-Message: 15:53:51.041: JS LOG: [LookingGlass/info] DeskletManager started in 3 ms
Gjs-Message: 15:53:51.041: JS LOG: [LookingGlass/info] SearchProviderManager started in 2 ms
Gjs-Message: 15:53:51.525: JS LOG: [LookingGlass/info] Role locked: tray
Gjs-Message: 15:53:51.536: JS LOG: [LookingGlass/info] Loaded applet systray@cinnamon.org in 98 ms
Gjs-Message: 15:53:51.698: JS LOG: [LookingGlass/info] Loaded applet removable-drives@cinnamon.org in 159 ms
Gjs-Message: 15:53:51.721: JS LOG: [LookingGlass/info] Loaded applet favorites@cinnamon.org in 22 ms
Gjs-Message: 15:53:51.768: JS LOG: [LookingGlass/info] Role locked: notifications
Gjs-Message: 15:53:51.801: JS LOG: [LookingGlass/info] Loaded applet notifications@cinnamon.org in 80 ms
Gjs-Message: 15:53:51.831: JS LOG: [LookingGlass/info] Loaded applet cornerbar@cinnamon.org in 29 ms
Gjs-Message: 15:53:51.953: JS LOG: [LookingGlass/info] Loaded applet calendar@cinnamon.org in 122 ms
Gjs-Message: 15:53:52.006: JS LOG: [LookingGlass/info] Loaded applet printers@cinnamon.org in 52 ms
Gjs-Message: 15:53:52.116: JS LOG: [LookingGlass/info] Loaded applet keyboard@cinnamon.org in 110 ms
Gjs-Message: 15:53:52.152: JS LOG: [LookingGlass/info] Loaded applet xapp-status@cinnamon.org in 36 ms
Gjs-Message: 15:53:52.176: JS LOG: [LookingGlass/info] Loaded applet workspace-switcher@cinnamon.org in 24 ms
Gjs-Message: 15:53:52.177: JS LOG: calendar@cinnamon.org: Calendar events supported.
Gjs-Message: 15:53:52.247: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 71 ms
Gjs-Message: 15:53:52.315: JS LOG: [LookingGlass/info] Role locked: windowattentionhandler
Gjs-Message: 15:53:52.422: JS LOG: [LookingGlass/info] Loaded applet window-list@cinnamon.org in 175 ms
Gjs-Message: 15:53:52.427: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nm-applet (:1.114/org/x/StatusIcon/Icon)
Gjs-Message: 15:53:52.440: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintreport (:1.103/org/x/StatusIcon/Icon)
Gjs-Message: 15:53:52.444: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: process-monitor (:1.103/org/x/StatusIcon/Icon_1)
Gjs-Message: 15:53:52.448: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: telegramdesktop (:1.49/org/x/StatusIcon/Icon_2)
Gjs-Message: 15:53:52.454: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: zero trust client (:1.49/org/x/StatusIcon/Icon)
Gjs-Message: 15:53:52.461: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: psensor (:1.49/org/x/StatusIcon/Icon_3)
Gjs-Message: 15:53:52.475: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: blueman (:1.49/org/x/StatusIcon/Icon_1)
Gjs-Message: 15:53:52.484: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: mintUpdate.py (:1.90/org/x/StatusIcon/Icon)
Gjs-Message: 15:53:52.493: JS LOG: [LookingGlass/info] Adding XAppStatusIcon: nvidia-prime (:1.58/org/x/StatusIcon/Icon)
Gjs-Message: 15:53:52.695: JS LOG: [LookingGlass/info] Loaded applet sound@cinnamon.org in 273 ms
Gjs-Message: 15:53:52.762: JS LOG: [LookingGlass/info] Hiding XAppStatusIcon (we have an applet): nm-applet (:1.114/org/x/StatusIcon/Icon)
Gjs-Message: 15:53:52.788: JS LOG: [LookingGlass/info] Loaded applet network@cinnamon.org in 92 ms
Gjs-Message: 15:53:53.209: JS LOG: [LookingGlass/info] Loaded applet menu@cinnamon.org in 420 ms
Gjs-Message: 15:53:53.210: JS LOG: [LookingGlass/info] AppletManager started in 2206 ms
Gjs-Message: 15:53:53.219: JS LOG: [LookingGlass/info] Cinnamon took 2891 ms to start
Gjs-Message: 15:53:53.347: JS LOG: Unknown network device type, is 32
Gjs-Message: 15:53:53.436: JS LOG: Unknown network device type, is 30
Gjs-Message: 15:53:53.436: JS LOG: Unknown network device type, is 13
Gjs-Message: 15:53:53.436: JS LOG: Unknown network device type, is 13
Gjs-Message: 15:53:53.436: JS LOG: Unknown network device type, is 13
Gjs-Message: 15:53:53.436: JS LOG: Unknown network device type, is 13
Gjs-Message: 15:53:53.436: JS LOG: Unknown network device type, is 13
Gjs-Message: 15:53:54.233: JS LOG: [LookingGlass/info] GPU offload supported: false
Gjs-Message: 15:53:54.716: JS LOG: Enabling WindowAttentionHandler

** (cinnamon:7627): CRITICAL **: 15:54:00.559: cogl_pipeline_set_layer_combine_constant: assertion 'cogl_is_pipeline (pipeline)' failed
Segmentation fault (core dumped)
```

</details>

[crash.tar.gz](https://github.com/user-attachments/files/18649599/crash.tar.gz)

**Comment by mtwebster** [comment]
Hi, please provide additional crash info:
https://projects.linuxmint.com/reference/git/bugs/mintreport-crash-info.html

**Comment by claudiux** [comment]
Fixed by https://github.com/linuxmint/cinnamon-spices-themes/pull/846

**Comment by vlad0337187** [comment]
@claudiux , sorry, I named that PR wrongly,  it doesn't fix this problem,
I just removed lines causing crash in that PR.

But problem still exists, you can't use "text-shadow" property in specified class and id anymore (on Mint 22 it was possible).
