### ISSUE TITLE
bug in used alsa-base 1.0.25 for USB Audio Devices SplitPCM: Device argument may not be set

### ISSUE THREAD

**Issue by snooops** [linuxmint/cinnamon#12793]
### Distribution

Mint 22.1

### Package version

6.4.8

### Graphics hardware in use

ASUS TUF Nvidia GeForce RTX 3080

### Frequency

Always

### Bug description

Some USB Audio won't work properly because of a syntax error, the bug is decribed here: https://github.com/Fumler/alsa-ucm-conf/commit/b68aa52acdd2763fedad5eec0f435fbf43e5ccc6

I stumbled across this during the setup of my new Roland Bridge Cast USB Audio device, which was not properly recognized by the system.

This bug was tracked in the Linux Mint Community Discord. Here is the chat protocol

Hi, 
i have a Roland Bridge Cast (https://www.roland.com/de/products/bridge_cast/) which is connected via USB to my computer. The USB device should offer a few output stereo sound channels: AUX, CHAT, GAME as well as one MIC input channel. As far as i can see, there is an ALSA profile for this device available: /usr/share/alsa/ucm2/USB-Audio/Roland/BridgeCast-Hifi.conf but it seems it is not loaded. The only devices i see in the "Sound" application of Linux Mint Cinnamon is Analog Output BRIDGE CAST with a single Output profile: Analog Surround 7.1 Output. For Input i see also just a single Analog Output BRIDGE CAST . Any suggestions?
My System spec: https://termbin.com/bjln

Some debugging 
```
$ sudo alsaucm listcards
ALSA lib utils.c:364:(uc_mgr_config_load_into) could not open configuration file /usr/share/alsa/ucm2/USB-Audio/Roland/BridgeCast.conf
ALSA lib parser.c:78:(uc_mgr_config_load_file) error: failed to open file /usr/share/alsa/ucm2/USB-Audio/Roland/BridgeCast.conf: -2
ALSA lib main.c:1554:(snd_use_case_mgr_open) error: failed to import hw:2 use case configuration -2
  list is empty
```

I created a symlink: 
`ln -s /usr/share/alsa/ucm2/USB-Audio/Roland/BridgeCast-Hifi.conf /usr/share/alsa/ucm2/USB-Audio/Roland/BridgeCast.conf`
But now i get: 
```
$ alsactl restore
alsa-lib parser.c:2495:(parse_master_file) unknown master file field SectionDevice
alsa-lib main.c:1561:(snd_use_case_mgr_open) error: failed to import hw:2 (empty configuration)
```

It seems fixed in the newset version of alsa-libshttps://github.com/alsa-project/alsa-ucm-conf/pull/445 i guess i have to wait then
GitHub
[ucm2: Add Roland Bridge Cast V2 by Fumler · Pull Request #445 · als...](https://github.com/alsa-project/alsa-ucm-conf/pull/445)
Roland Bridge Cast recently had a firmware update which brings in e.g. virtual surround and is dubbed as &quot;V2&quot; and has a separate usb device id than the existing Bridge Cast in the...
ucm2: Add Roland Bridge Cast V2 by Fumler · Pull Request #445 · als...

Ok i got - after applying this: https://github.com/Fumler/alsa-ucm-conf/commit/b68aa52acdd2763fedad5eec0f435fbf43e5ccc6 and ensured i have those files present: https://github.com/Fumler/alsa-ucm-conf/tree/master/ucm2/USB-Audio/Roland as well as the corresponding entries in here: https://github.com/Fumler/alsa-ucm-conf/blob/1d9209a335231cd524873154c550a28ca3ef9494/ucm2/USB-Audio/USB-Audio.conf#L155-L170 
it works now and i have all channels available. I recommend to apply the latest alsa library to linux mint.
GitHub
[SplitPCM: Device argument may not be set · Fumler/alsa-ucm-conf@b68...](https://github.com/Fumler/alsa-ucm-conf/commit/b68aa52acdd2763fedad5eec0f435fbf43e5ccc6)
Link: https://github.com/alsa-project/alsa-ucm-conf/issues/346
Fixes: 10967ea ("SplitPCM: Fix Device variable in SplitPCMDevice macro")
Signed-off-by: Jaroslav Kysela
GitHub
[alsa-ucm-conf/ucm2/USB-Audio/Roland at master · Fumler/alsa-ucm-conf](https://github.com/Fumler/alsa-ucm-conf/tree/master/ucm2/USB-Audio/Roland)
ALSA Use Case Manager configuration. Contribute to Fumler/alsa-ucm-conf development by creating an account on GitHub.
GitHub
[alsa-ucm-conf/ucm2/USB-Audio/USB-Audio.conf at 1d9209a335231cd52487...](https://github.com/Fumler/alsa-ucm-conf/blob/1d9209a335231cd524873154c550a28ca3ef9494/ucm2/USB-Audio/USB-Audio.conf)
ALSA Use Case Manager configuration. Contribute to Fumler/alsa-ucm-conf development by creating an account on GitHub.

### Steps to reproduce

Use a Roland Bridge Cast device via USB and connect it to your PC.

### Expected behavior

All channels should appear in the sound configuration window.

**Comment by leigh123linux** [comment]
This issue can't be fixed within the cinnamon code, file your issue against the broken package, alsa?

**Comment by snooops** [comment]
I don't want to reopen this issue but i ran again into that with an update, so here is the official alsa bug report in the ubuntu alsa package: https://bugs.launchpad.net/ubuntu/+source/alsa-ucm-conf/+bug/2068911

**Comment by kladderadeng** [comment]
I have no idea if anyone will see this, since it is a closed issue. Despite the bug is being fixed "upstream" (if this is the right term), Linux Mint Cinnamon 22.2 still contains the alsa-ucm-conf 2.10.0 package which has the issue. It is fixed in 2.11.0+ too and I have no idea where to open an "issue" or ask for an upgraded version of alsa-ucm-conf in an upcoming Linux Mint update.

**Comment by leigh123linux** [comment]
> alsa-ucm-conf 2.10.0

I doubt ubuntu will update their broken package as it isn't a security issue.
LTS bugs remain for the whole 5 year cycle.


https://ubuntu.com/about/release-cycle

**Comment by kladderadeng** [comment]
Oh wow! That's wild! I was not aware. Thanks for pointing that out. So it's manual bugfixing until then. The good thing is, if the package does not change anyway, I need to apply the fix only once ;-)
