### ISSUE TITLE
systemd-inhibit block behavior changed -> Power Settings broken

### ISSUE THREAD

**Issue by ssusbauer** [linuxmint/Cinnamon#13219]
### Distribution

LMDE 7

### Package version

Cinnamon 6.4.13

### Frequency

Quite often

### Bug description

Systemd 257 made "block" more powerful (https://lwn.net/Articles/1001657/ - See systemd-logind), when a block is in place all of the "When the lid is closed" and "When the power button is pressed" options in Power Settings go from Suspend to blank, as Suspend is not available when there is a block. Even if configured beforehand, the associated actions never trigger.

It is possible for Cinnamon to override these blocks, I think Cinnamon behavior should be modified to do this when the configuration has been set. I am talking especially about Suspend on Lid Close and the Power Button settings, I understand why keeping the Time-based settings as is may be desirable (thinking inhibit applet). The behavior right now, with the new systemd version, causes the system to keep running like normal with the lid closed even when configured otherwise, and the Power Button is ignored outright.

This is especially an issue because Chromium-based browsers are very aggressive in their use of inhibit blocks. Instead of  happening only when they're playing media, they can happen often for reasons unknown. I would also argue, if I have the lid closed or power button action configured to suspend, I want the system to suspend even when the browser is playing media.

### Steps to reproduce

Open Chromium-based browser, use it for a while although it may even happen at initial startup. Note that inhibit blocks are added in `systemd-inhibit --list` at various times blocking shutdown:sleep. When in place, the Power Management settings become blank and the behavior is as described.

### Expected behavior

Override the browser - go to sleep when I hit the power button or close the lid if I've configured the system to do so.

**Comment by mtwebster** [comment]
Possibly addressed by:
https://github.com/linuxmint/cinnamon-session/commit/28b5ebc18c744e1c79efbaa8d6b3e91bdad2e57e
or
~~https://github.com/linuxmint/cinnamon-session/commit/8042c7f4756773b32e30f902d2cb05c865b9f6d7
(see the linked issue also).~~ - edit I realized this is already in lmde7

These will be in the upcoming release (6.6). I'll have to have a look at Power settings, I didn't think to see if that was affected.

**Comment by ssusbauer** [comment]
I can confirm the Reboot and Shutdown options work as expected here and Suspend does not show up in the popup dialog (also expected). I opened another bug for the Exit@claudiux applet (https://github.com/linuxmint/cinnamon-spices-applets/issues/8001) as it is also affected, and I'm sure a couple other applets that try to do those things.

Glad some of this has already been on the radar.

**Comment by xhpohanka** [comment]
This is still an issue for me in 6.6.3, at least inhibit@cinnamon.org still shows that there is active suppression caused by chromium based app. In previous version suspend/hibernate was missing from shutdown menu, but now they are back...

**Comment by warwickmm** [comment]
I also encounter times when I cannot suspend my laptop.  The suspend option appears, but doesn't do anything when clicked.

This is using 6.6.6-1 on Arch:
```
user@lenny:~$ systemd-inhibit
WHO            UID  USER PID    COMM            WHAT                                                     WHY                                         MODE
NetworkManager 0    root 833740 NetworkManager  sleep                                                    NetworkManager needs to turn off networks   delay
Realtime Kit   0    root 1760   rtkit-daemon    sleep                                                    Demote realtime scheduling and stop canary. delay
UPower         0    root 1867   upowerd         sleep                                                    Pause device polling                        delay
user           1000 user 2084   csd-power       handle-lid-switch                                        Multiple displays attached                  block
user           1000 user 2088   csd-media-keys  handle-power-key:handle-suspend-key:handle-hibernate-key Cinnamon handling keypresses                block
user           1000 user 2039   cinnamon-sessio shutdown:sleep                                           user session inhibited                      block
```

**Comment by calestyo** [comment]
Having the same here.

Here it still works:
```
# cat inhi 
WHO            UID  USER     PID  COMM           WHAT                                                     WHY                                       MODE
NetworkManager 0    root     2919 NetworkManager sleep                                                    NetworkManager needs to turn off networks delay
UPower         0    root     5723 upowerd        sleep                                                    Pause device polling                      delay
calestyo       1000 calestyo 5586 csd-power      handle-lid-switch                                        Multiple displays attached                block
calestyo       1000 calestyo 5580 csd-media-keys handle-power-key:handle-suspend-key:handle-hibernate-key Cinnamon handling keypresses              block
calestyo       1000 calestyo 5586 csd-power      sleep                                                    Cinnamon needs to lock the screen         delay

5 inhibitors listed.
```

My firefox (which seems to somehow affect this) is already running.


But here not anymore:
```
# systemd-inhibit --list
WHO            UID  USER     PID    COMM            WHAT                                                     WHY                                       MODE 
NetworkManager 0    root     168318 NetworkManager  sleep                                                    NetworkManager needs to turn off networks delay
UPower         0    root     168210 upowerd         sleep                                                    Pause device polling                      delay
calestyo       1000 calestyo 3403   csd-power       handle-lid-switch                                        Multiple displays attached                block
calestyo       1000 calestyo 3397   csd-media-keys  handle-power-key:handle-suspend-key:handle-hibernate-key Cinnamon handling keypresses              block
calestyo       1000 calestyo 3336   cinnamon-sessio shutdown:sleep                                           user session inhibited                    block
calestyo       1000 calestyo 3403   csd-power       sleep                                                    Cinnamon needs to lock the screen         delay

6 inhibitors listed.
```

If I now close firefox, it works again and `systemd-inhibit --list` is back to the original.

Not sure how it triggers that, perhaps it only happens when I start firefox a 2nd time.

PS: I'm not using the inhibit applet.

**Comment by mtwebster** [comment]
Please test this with Cinnamon 6.6.7 and cinnamon-session 6.6.3

**Comment by calestyo** [comment]
@mtwebster 
```
$ dpkg -l cinnamon cinnamon-session | grep ii
ii  cinnamon         6.6.7-1      amd64        Innovative and comfortable desktop
ii  cinnamon-session 6.6.3-1      amd64        Cinnamon Session Manager - Minimal runtime
```

Problem still exists.
Maybe a bit different though. Previously, I think only Suspend/Hibernate were gone most of the time. With the current version I just got at least the case where **only** `Cancel` was left.

However, I've also had the same (`Cancel`-only already before on older Cinnamon). And the case where only Hibernate/Suspend are gone might still show up.

If you'd have accepted my #13108 one could have easily extended it to simply ignore any non-working autodetection of what's available. :-(

**Comment by calestyo** [comment]
My previous message **might** be bogus... could be that the `Cancel`-**only** case was actually caused by apt/aptitude. So tentatively ignore it.

**Comment by warwickmm** [comment]
After a period of not experiencing this, I just encountered it again with cinnamon 6.6.8-1 and cinnamon-session 6.6.3-2 on Arch. 
```
$ systemd-inhibit                                                                                                                                                                                                                                                                                                                                                          
WHO            UID  USER PID  COMM            WHAT                                                     WHY                                         MODE 
NetworkManager 0    root 1588 NetworkManager  sleep                                                    NetworkManager needs to turn off networks   delay
Realtime Kit   0    root 1765 rtkit-daemon    sleep                                                    Demote realtime scheduling and stop canary. delay
UPower         0    root 1869 upowerd         sleep                                                    Pause device polling                        delay
xyz            1000 xyz  2149 csd-power       handle-lid-switch                                        Multiple displays attached                  block
xyz            1000 xyz  2157 csd-media-keys  handle-power-key:handle-suspend-key:handle-hibernate-key Cinnamon handling keypresses                block
xyz            1000 xyz  2102 cinnamon-sessio shutdown:sleep                                           user session inhibited                      block
```

After closing the browser (Brave), the suspend/restart/etc. options appear again.

**Comment by calestyo** [comment]
@mtwebster, I can now also confirm that it still occurs with cinnamon 6.6.8 (i.e. this time I had no apt/aptitude running), but so far I've only seen it with all buttons except `Cancel` gone (no longer what we had previously, that only some of the buttons were gone).
