### ISSUE TITLE
Power Manager applet sometimes not updating battery percentage

### ISSUE THREAD

**Issue by malsyned** [linuxmint/Cinnamon#13324]
### Distribution

Manjaro (rolling)

### Package version

6.6.2

### Graphics hardware in use

AMD Radeon 780M

### Frequency

Quite often

### Bug description

Since upgrading from 6.4 to 6.6, the battery percentage displayed on the panel isn't always accurate. It seems to not be updating reliably as the battery drains.

For example, today, I watched with `upower --monitor-details` as my battery level dropped from 39% to 29%, and the power manager applet icon remained at 39% the entire time, only changing when the battery percentage got to 29%.

<img width="1772" height="514" alt="Image" src="https://github.com/user-attachments/assets/771ba456-ef6e-470c-a5c1-7f8f30aa7291" />

### Steps to reproduce

1. Run on battery power
2. Watch the battery applet
3. Sometimes it doesn't change as the battery drains

### Expected behavior

The battery applet updates to reflect the battery percentage whenever that percentage goes down.

### Additional information

```
> grep -i power ~/.xsession-errors
Cjs-Message: 13:51:53.099: JS LOG: [LookingGlass/info] Loaded applet power@cinnamon.org in 23 ms
csd-power-Message: 13:51:53.129: gnome-rr not supported for display backlight, using backlight-helper for future calls
(csd-power:24268): csd-power-WARNING **: 17:25:38.714: Unable to inhibit suspend: GDBus.Error:org.freedesktop.login1.OperationInProgress: The operation inhibition has been requested for is already running
```

**Comment by roman11x** [comment]
# Distribution
EndeavourOS(rolling)

# Package version
6.6.3

# Graphics hardware in use
AMD Ryzen 7 5700U (Integrated Graphics)

# Frequency
Often

# Bug description
I have the same issue as the poster

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fc4940df-48a4-40f9-9364-69302b4eb3ea" />

**Comment by Gijs6** [comment]
## Distribution

Arch (rolling)

## Package version

6.6.3-5

## Graphics hardware in use

I have this issue both on Intel Alder Lake-P GT1 and on NVIDIA GeForce RTX 3050 Mobile (I use optimus-manager to switch between them)

## Frequency

Always

## Bug description

The same as described earlier. The battery level in my applet only goes down every ~10% (so it goes from 99% to 89% etc). It does also display the correct value after reloading the applet.

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/b490113d-190f-43f6-bad0-69b4dbf00359" />

**Comment by malsyned** [comment]
Some additional information: if the charge cable status changes, that seems to force an update. For example, if I'm running on battery power and the SoC is 23%, but the applet is showing 29%, when I plug the charge cable in the applet changes to the charging icon and updates to the correct SoC (23%).

**Comment by roman11x** [comment]
What malsyned added is the case for me as well. Plugging in the charge cable forces an update.

**Comment by dukenukem2d** [comment]
I recently updated Cinnamon to version 6.6.4 on LMDE 7, and now I'm encountering an issue with battery status updates.

<img width="1724" height="536" alt="Image" src="https://github.com/user-attachments/assets/eecc9e54-77cf-4d81-8e46-1713b82143fa" />

**Comment by hoaianle** [comment]
Just update to Linux Mint 22.3 and have the same issue. Toggle Panel edit mode will make the battery refresh but it not refresh when I click to the applet. Maybe some daemon issue?

**Comment by ridwanpr** [comment]
Updating to mint 22.3 triggered this issue for me. The battery percentage in power management shows the correct value, while the percentage in the applet is stuck.

**Comment by zboraon** [comment]
> Updating to mint 22.3 triggered this issue for me. The battery percentage in power management shows the correct value, while the percentage in the applet is stuck.

Same applies here.

**Comment by Mayedl10** [comment]
> Updating to mint 22.3 triggered this issue for me. The battery percentage in power management shows the correct value, while the percentage in the applet is stuck.

Same for me

Edit: When I go to the "Batteries" tab, click in the name field, then close the window, the widget also sometimes updates

**Comment by Angedestenebres** [comment]
Hey 🐱 

I also have the issue since my upgrade to LM 22.3.
In fact, the % of battery in applet is stuck (no matter if it's charging or not) & can be update by (un)plug the power adapter (status changes).

Before unplug:

<img width="920" height="232" alt="Image" src="https://github.com/user-attachments/assets/bd852824-a626-4172-9124-ecb18e2a6fda" />

After:

<img width="899" height="227" alt="Image" src="https://github.com/user-attachments/assets/f55b2b28-7af0-4e90-b735-b9b866faff21" />

@clefebvre & @mtwebster: Even if it's only a display issue, it can generate frustration if battery is low. I guess a quick fix could be welcome :)

**Comment by imliuyzh** [comment]
This is also happening on my device too. A workaround I use is to turn on and turn off the panel edit mode.

I debugged this applet and it turned out the updated battery value was not sent to the applet. Here is how to do it:

1. `cp -r /usr/share/cinnamon/applets/power@cinnamon.org  ~/.local/share/cinnamon/applets/`
2. Change folder name from `power@cinnamon.org` to `temp@cinnamon.org`
3. Go to the folder and change `metadata.json` to
    
     ```
     {
      "uuid": "temp@cinnamon.org",
      "name": "Power Manager (Dev)",
      "description": "Cinnamon power management applet (Dev)",
      "icon": "preferences-system-power"
     }
     ```

4. Log values using `global.log()` after lines like `let [device_id, vendor, model, device_kind, icon, percentage, state, battery_level, time] = device;`
5. Add this new applet to a panel (the name is `Power Manager (Dev)`)
6. Right click on a panel, `Troubleshoot` -> `Looking Glass`, and you should see the logs there
7. If you changed the applet, reload it under the extensions tab in looking glass

**Comment by imhatsune03** [comment]
Even after updating from cinnamon 6.6.5 the battery applet problem persists

<img width="890" height="642" alt="Image" src="https://github.com/user-attachments/assets/ce2a4ca9-a82a-4aa9-95ae-8488fc0f7d62" />

**Comment by ploxiln** [comment]
As @imliuyzh said, "the updated battery value was not sent to the applet". Specifically, this dbus g-properties-changed subscription isn't triggering when battery level changes:

```js
this._proxy.connect("g-properties-changed", Lang.bind(this, this._devicesChanged));
```

Here's my hacky work-around that adds polling ever 15 seconds:

```diff
--- /usr/share/cinnamon/applets/power@cinnamon.org/applet.js.orig	2026-01-16 15:51:38.749721288 -0500
+++ /usr/share/cinnamon/applets/power@cinnamon.org/applet.js	2026-01-16 16:27:53.386402645 -0500
@@ -1,3 +1,4 @@
+const GLib = imports.gi.GLib;
 const Applet = imports.ui.applet;
 const Clutter = imports.gi.Clutter;
 const Gio = imports.gi.Gio;
@@ -467,6 +468,13 @@
             }));
         }, null);
 
+        // HACK: poll every 15 seconds
+        this._timerId = GLib.timeout_add(GLib.PRIORITY_DEFAULT, 15000, () => {
+            global.logWarning("POWER POLL TIMEOUT");
+            this._devicesChanged();
+            return true; // repeat
+        });
+
         this.set_show_label_in_vertical_panels(false);
     }
 
@@ -652,6 +660,7 @@
         this._devices = [];
         this._primaryDevice = null;
         this._primaryDeviceId = null;
+        global.log("POWER DEVICES CHANGED");
 
         if (!this._proxy)
             return;
@@ -828,6 +837,9 @@
     on_applet_removed_from_panel() {
         Main.systrayManager.unregisterTrayIconReplacement(this.metadata.uuid);
 
+        if (this._timerId)
+            GLib.source_remove(this._timerId);
+
         if (!this._profilesProxy)
             return;

```

(the logging can be seen in "Looking Glass")

**Comment by imliuyzh** [comment]
Thanks for referencing my post (https://github.com/linuxmint/cinnamon/issues/13324#issuecomment-3761877056). Just want to add one more observation: the Power Management (which is written in Python) page also did something similar but was completely unaffected (https://github.com/linuxmint/cinnamon/blob/090423505db2a260fa7fa7bfdb7923b62b91c3b7/files/usr/share/cinnamon/cinnamon-settings/modules/cs_power.py#L234C14-L234C29).

Also, this issue looks strikingly similar to https://github.com/linuxmint/cinnamon-settings-daemon/pull/364. Maybe the patch can use the idea there.

**Comment by ploxiln** [comment]
> the Power Management (which is written in Python) page also did something similar but was completely unaffected

Hmm ... it seems to me on my system (Arch Linux, cinnamon-6.6.4 cinnamon-desktop-6.6.2 cinnamon-settings-daemon-6.6.2 ...) like the "Power Management" settings pane "Batteries" tab has the same issue. The battery level is correct when you open it, but if you leave it open, it doesn't update when battery level changes, until you re-plug power or similar. Seems probable to have the same cause, "g-properties-changed" not triggering on `org.cinnamon.SettingsDaemon.Power` somehow.

Nice find with that old PR ... the most recent commit to that file looks quite suspicious!
https://github.com/linuxmint/cinnamon-settings-daemon/commit/c2c760960dd3e19cccdd05b55105e5956586a396

That says it's dropping an unused Tooltip property, but it's also dropping `engine_recalculate_state_summary()` ... maybe that tooltip being updated had the side-effect of causing a property state change when battery level changes 1%, and nothing else does that now that tooltip is removed?

**Comment by imliuyzh** [comment]
@ploxiln I actually used Linux Mint 22.3 directly and it wasn't behaving like yours. Anyway, I decided to restore the snapshot and rollback to 22.2. Not going to upgrade it for some time.

P.S. For Linux Mint 22.2, these are the package versions:

- cinnamon 6.4.8
- cinnamon-settings-daemon 6.4.3

I saw https://github.com/linuxmint/cinnamon-settings-daemon/pull/422 was introduced since 6.6.0 and could somebody install this version and see whether this bug had left undiscovered since then?

**Comment by dukenukem2d** [comment]
> Even after updating from cinnamon 6.6.5 the battery applet problem persists

Same. LDME 7, cinnamon 6.6.5

**Comment by mtwebster** [comment]
> > the Power Management (which is written in Python) page also did something similar but was completely unaffected
> 
> Hmm ... it seems to me on my system (Arch Linux, cinnamon-6.6.4 cinnamon-desktop-6.6.2 cinnamon-settings-daemon-6.6.2 ...) like the "Power Management" settings pane "Batteries" tab has the same issue. The battery level is correct when you open it, but if you leave it open, it doesn't update when battery level changes, until you re-plug power or similar. Seems probable to have the same cause, "g-properties-changed" not triggering on `org.cinnamon.SettingsDaemon.Power` somehow.
> 
> Nice find with that old PR ... the most recent commit to that file looks quite suspicious! [linuxmint/cinnamon-settings-daemon@c2c7609](https://github.com/linuxmint/cinnamon-settings-daemon/commit/c2c760960dd3e19cccdd05b55105e5956586a396)
> 
> That says it's dropping an unused Tooltip property, but it's also dropping `engine_recalculate_state_summary()` ... maybe that tooltip being updated had the side-effect of causing a property state change when battery level changes 1%, and nothing else does that now that tooltip is removed?

This is probably it, nice catch.

**Comment by assil-coder** [comment]
have you found a solution for this?
I got the same problem after upgrading to mint 22.3

**Comment by ploxiln** [comment]
Yes, this was fixed in https://github.com/linuxmint/cinnamon-settings-daemon/pull/438 - you'll have to wait for that to be included in an update release that makes it to your system.

**Comment by Phenzo** [comment]
After the fix, it updates when charging and discharging, but its still buggy. When hitting full charge it still says "charging" and "x minutes untill fully charged". This also keeps the x time to fully charged stuck in the tray icon, when its stopped charging becuase its fully charged. Under power settings the information is correct, and to update the battery tray icon, I have to reload cinnamon or rightclick the icon and tick on or off "show all batteries" or the dropdown.

**Comment by frankvw2017** [comment]
I have the same problem. Following the upgrade from Mint 22.2 to 22.3 there are significant discrepancies between the output of **acpi -b** and the battery manager.

But that's not the only issue. My screen also no longer dims or blanks upon inactivity.

**Comment by Ryker-Soto** [comment]
does anyone know if this issue was resolved for specifically Linux Mint 22.3? Like as an official update that has already come out?

**Comment by ploxiln** [comment]
This particular bug is fixed in cinnamon-settings-daemon 6.6.3 and I think that has been rolled-out to LM 22.3 (I use a different distro): http://packages.linuxmint.com/search.php?release=zena&section=any&keyword=cinnamon-settings-daemon

**Comment by archisman-panigrahi** [comment]
The issue still seems to exist in fully updated Mint 22.3. I experienced it in my Dell Latitude 5420. It was again reported in https://github.com/linuxmint/cinnamon/issues/13324

**Comment by Ryker-Soto** [comment]
Thank you, a lot of people seem to still have the same issue unfortunately. I really want to upgrade to 22.3, but until they fix that, I am going to stick to 22.2

**Comment by insomniacno1** [comment]
This issue is not only in newer versions of Cinnamon, but exist in Linux Mint 21.3(I am not upgrading until the bugs(many) has been fixed), Cinnamon 6.0.4. 

For the developer this should be easy to fix, but it seem that it is not important since it has existed for many years now and continue all the way up to newest version of Linux Mint and other distros using Cinnamon.

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/f8ae0719-2fea-47cc-bbf5-5f42ce4528ad" />

WHY can't the applet report exactly the same information as Power Settings > Batteries???

System information, notice in battery it says not charging, but it is charging as seen in above screenshot in Power Settings!

System:
  Kernel: 6.8.0-100-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33
    wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy

Machine:
  Type: Laptop System: LENOVO product: 20AUA0F4JP v: ThinkPad L540 serial: <superuser required>
    Chassis: type: 10 serial: <superuser required>
  
Mobo: LENOVO model: 20AUA0F4JP v: 0B98401 Pro serial: <superuser required>
    UEFI-[Legacy]: LENOVO v: J4ET93WW(1.93) date: 05/30/2018

Battery:
  ID-1: BAT0 charge: 94.3 Wh (96.7%) condition: 97.5/100.0 Wh (97.5%) volts: 12.3 min: 11.1
    model: SANYO 45N1779 type: Li-ion serial: <filter> status: Not charging         < THIS IS NOT CORRECT!!!

CPU:
  Info: dual core model: Intel Core i5-4200M bits: 64 type: MT MCP smt: enabled arch: Haswell
    rev: 3 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
  Speed (MHz): avg: 3029 high: 3066 min/max: 800/3100 cores: 1: 3066 2: 3066 3: 2993 4: 2993
    bogomips: 19953
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx

Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Lenovo driver: i915 v: kernel
    ports: active: eDP-1 empty: DP-1, DP-2, HDMI-A-1, HDMI-A-2, VGA-1 bus-ID: 00:02.0
    chip-ID: 8086:0416 class-ID: 0300
  Device-2: Acer Integrated Camera type: USB driver: uvcvideo bus-ID: 1-12:5 chip-ID: 5986:0397
    class-ID: 0e02
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96 s-size: 361x203mm (14.2x8.0") s-diag: 414mm (16.3")
  Monitor-1: eDP-1 model: AU Optronics res: 1366x768 hz: 60 dpi: 101 size: 344x193mm (13.5x7.6")
    diag: 394mm (15.5") modes: 1366x768
  OpenGL: renderer: Mesa Intel HD Graphics 4600 (HSW GT2) v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.3
    direct render: Yes

Audio:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio vendor: Lenovo
    driver: snd_hda_intel v: kernel bus-ID: 00:03.0 chip-ID: 8086:0c0c class-ID: 0403
  Device-2: Intel 8 Series/C220 Series High Definition Audio vendor: Lenovo
    driver: snd_hda_intel v: kernel bus-ID: 00:1b.0 chip-ID: 8086:8c20 class-ID: 0403
  Sound Server-1: ALSA v: k6.8.0-100-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes

Network:
  Device-1: Intel Ethernet I217-V vendor: Lenovo driver: e1000e v: kernel port: 5080
    bus-ID: 00:19.0 chip-ID: 8086:153b class-ID: 0200
  IF: enp0s25 state: down mac: <filter>
  Device-2: Intel Wireless 7260 driver: iwlwifi v: kernel pcie: speed: 2.5 GT/s lanes: 1
    bus-ID: 02:00.0 chip-ID: 8086:08b2 class-ID: 0280
  IF: wlp2s0 state: up mac: <filter>

Bluetooth:
  Device-1: Intel Bluetooth wireless interface type: USB driver: btusb v: 0.8 bus-ID: 1-11:4
    chip-ID: 8087:07dc class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 2.1 lmp-v: 4.0
    sub-v: 500 hci-v: 4.0 rev: 500
Drives:
  Local Storage: total: 465.76 GiB used: 319.34 GiB (68.6%)
  ID-1: /dev/sda vendor: Crucial model: CT500BX500SSD1 size: 465.76 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 072 scheme: MBR
Partition:
  ID-1: / size: 243.39 GiB used: 205.72 GiB (84.5%) fs: ext4 dev: /dev/sda5
  ID-2: /boot/efi size: 512 MiB used: 16 KiB (0.0%) fs: vfat dev: /dev/sda2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile

USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 14 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-6:2 info: Areson Corp Elecom MR-K013 Multicard Reader type: Keyboard,Mouse
    driver: hid-generic,usbhid interfaces: 2 rev: 1.1 speed: 12 Mb/s power: 100mA chip-ID: 25a7:fa61
    class-ID: 0301
  Device-2: 1-7:3 info: Validity Sensors VFS5011 Fingerprint Reader type: <vendor specific>
    driver: N/A interfaces: 1 rev: 1.1 speed: 12 Mb/s power: 100mA chip-ID: 138a:0011 class-ID: ff00
    serial: <filter>
  Device-3: 1-11:4 info: Intel Bluetooth wireless interface type: Bluetooth driver: btusb
    interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 8087:07dc class-ID: e001
  Device-4: 1-12:5 info: Acer Integrated Camera type: Video driver: uvcvideo interfaces: 2
    rev: 2.0 speed: 480 Mb/s power: 256mA chip-ID: 5986:0397 class-ID: 0e02
  Hub-2: 2-0:1 info: Super-speed hub ports: 4 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900

Sensors:
  System Temperatures: cpu: 78.0 C mobo: 44.0 C
  Fan Speeds (RPM): cpu: 0 fan-2: 0

Repos:
  Packages: 3329 apt: 3310 flatpak: 19
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list
    1: deb https: //dl.winehq.org/wine-builds/ubuntu/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //ubuntu.tuxuri.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //ubuntu.tuxuri.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //ubuntu.tuxuri.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/thierry-f-fork-michael-gruz-focal.list
    1: deb http: //ppa.launchpad.net/thierry-f/fork-michael-gruz/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/uget-team-ppa-focal.list
    1: deb http: //ppa.launchpad.net/uget-team/ppa/ubuntu jammy main

Info:
  Processes: 270 Uptime: 16h 26m wakeups: 3 Memory: 7.49 GiB used: 4 GiB (53.4%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12/9 Client: Unknown python3.10 client
  inxi: 3.3.13

I don't know if this applet relies on lm-sensors, if it does, then for god sake change that, lm-sensors suck ass, it has not been updated for years and bugs seldom get fixed. 
Even though that is a global linux program the developer don't care. 
And linux developers seem to be unable to move around this one, and use something else.
