### ISSUE TITLE
two lock screens set when locking cinnamon 2.0 under Ubuntu

### ISSUE THREAD

**Issue by grrrrr** [linuxmint/Cinnamon#2466]
Following an upgrade to `Cinnamon 2.0` when I manually lock my screen via `ctrl+alt+l` it applies two lock screens.  Visually I see a _new_ style lock screen with time and date on it.  When I go to unlock it prompts me for the password and immediately drops me to the _old_ style `cinnamon 1.8` lock screen which I also have to unlock

If the lock screen activates due to inactivity / screen timeout, I get prompted with the old `cinnamon 1.8` lock screen to enter my password.  I then briefly see my desktop upon successful entering of my password and then the _new_ `cinnamon 2.0` lockscreen kicks in and I am forced to unlock my account again

**what is happening**

When manually locking or timeout locking of screen, two lock screens are being applied

**What should happen**

When manually locking or timeout locking of screen only one lock screen should be applied.

**Also related**

Bug #2457 - screen not locking on suspend.

System info:

```
$ uname -a
Linux hostname 3.5.0-41-generic #64~precise1-Ubuntu SMP Thu Sep 12 16:50:04 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
```

Cinnamon info:

```
$ dpkg -l| grep cinnam
ii  cinnamon                                                    2.0.2-20131011040307-precise            Cinnamon desktop
ii  cinnamon-common                                             2.0.2-20131011040307-precise            Cinnamon desktop (Common data files)
ii  cinnamon-desktop-data                                       2.0.1-20131011011505-precise            Common files for Cinnamon desktop apps
ii  cinnamon-screensaver                                        2.0.0-20131011013003-precise            Cinnamon screen saver and locker
ii  cinnamon-session                                            2.0.1-20131011043004-precise            Cinnamon Session Manager - Minimal runtime
ii  cinnamon-settings-daemon                                    2.0.1-20131011004504-precise            daemon handling the Cinnamon session settings
ii  cinnamon-translations                                       2.0.1-20131011040406-precise            Translation files for the Cinnamon desktop
ii  gir1.2-cinnamondesktop-3.0                                  2.0.1-20131011011505-precise            Introspection data for CinnamonDesktop
ii  libcinnamon-desktop0                                        2.0.1-20131011011505-precise            Utility library for loading .desktop files - runtime files
```

PPA info

ppa:gwendal-lebihan-dev/cinnamon-stable

**Comment by cabellicar123** [comment]
Getting this issue on `Arch` running `Cinnamon 2.6.13`. `gnome-screensaver` is not installed:
```
$ pacman -Qqn | grep screensaver
cinnamon-screensaver
```
The gnome packages that are installed are:
```
$ pacman -Qqn | grep gnome      
gnome-backgrounds
gnome-bluetooth
gnome-chess
gnome-icon-theme
gnome-icon-theme-symbolic
gnome-keyring
gnome-mines
gnome-screenshot
gnome-sudoku
gnome-system-monitor
gnome-themes-standard
libgnome-keyring
libgnomekbd
polkit-gnome
```

**Comment by leigh123linux** [comment]
@cabellicar123 

post

```
ps -a |grep screen
```

**Comment by cabellicar123** [comment]
```
$ ps -A | grep screen
  757 ?        00:00:00 cinnamon-screen
```

**Comment by cabellicar123** [comment]
Here is some more info. It's a bit strange.
```
$ ps -A | grep cinnamon
  511 ?        00:00:00 cinnamon-sessio
  552 ?        00:00:02 cinnamon-settin
  602 ?        00:00:00 cinnamon-launch
  611 ?        00:08:52 cinnamon
  619 ?        00:00:00 cinnamon-killer
  725 ?        00:00:01 cinnamon-screen
```
```
$ ps -A | grep gnome
  509 ?        00:00:00 gnome-keyring-d
  620 ?        00:00:00 polkit-gnome-au
  5690 ?        00:00:00 gnome-pty-helpe
  7564 ?        00:00:00 gnome-pty-helpe
```
Setting `org.cinnamon.desktop.lockdown.disable-lock-screen` to `true` appeared to disable **both** lock screen on a test. Resetting that to the default in dconf editor appears to have "fixed" the issue (at least for now), so that I now only get **one** lock screen.

**Comment by cabellicar123** [comment]
As suspected this was only a temporary fix. Something else is going on.

**Comment by alphab0t** [comment]
This is still happening to me. Recenly, when it auto locks the screen after the set time, first I have to login to the GNOME lock screen then the Cinnamon lock screen. 

Using the following versions:
```
$ cinnamon --version
Cinnamon 2.6.12

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by SerCeMan** [comment]
Same issue after latest update:
```
serce@SerCe-FastLinux:~/tmp$ cinnamon --version
Cinnamon 2.6.12
serce@SerCe-FastLinux:~/tmp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

**Comment by JosephMcc** [comment]
This should actually be fixed now in the latest git version of cinnamon.

**Comment by cabellicar123** [comment]
Having the same issue as before continuing into `2.8.7`. I have noticed that with these settings:

`Turn off the screen when inactive for` - `5 min`
`Suspend when inactive for` - **`5 min`**
`Lock the computer when inactive` - `5 min`

the problem occurs; however, with these settings:

`Turn off the screen when inactive for` - `5 min`
`Suspend when inactive for` - **`10 min`**
`Lock the computer when inactive` - `5 min`

the issue seems to disappear. Perhaps for some reason suspending while the screen is locking is causing two screen lock signals to be sent or something?

**Comment by Zorlin** [comment]
Still happening to me.

wings@wings:~$ cinnamon --version
Cinnamon 3.6.2
wings@wings:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Comment by volviq** [comment]
Since I have a second user, when switching between a user and back, I'm having a very similar issue.
Can this be reopened?

**Comment by apalazzi** [comment]
I'm having the same issue on a freshly installed ubuntu:
```
andrea@navicella:~$ cinnamon --version
Cinnamon 3.4.6
andrea@navicella:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful
andrea@navicella:~$ ps -A |grep screen
 1361 ?        00:00:00 csd-screensaver
 1717 ?        00:00:06 cinnamon-screen
14893 ?        00:00:02 gnome-screensav
```

**Comment by InsaneJ** [comment]
I've installed Cinnamon on Ubuntu 18.04 and am getting the same issue.
`insanej@Clara-21:~$ cinnamon --version
Cinnamon 3.6.7
insanej@Clara-21:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
insanej@Clara-21:~$ ps -A | grep screen
 1813 ?        00:00:01 csd-screensaver
 2320 ?        00:00:04 gnome-screensav
 2334 ?        00:00:11 cinnamon-screen`
