### ISSUE TITLE
Cinnamon mixer doesn't instantly refresh list of audio devices after USB devices are plugged in

### ISSUE THREAD

**Issue by danboid** [linuxmint/Cinnamon#3918]
Hi Clem and the Cinnamon devs!

I'm running Cinnamon 2.4.6 under Arch x64 and something has bugged me about the mixer app (sound@cinnamon.org) for a while now.

When using my laptop, I frequently switch between using the internal audio and an external USB audio device. The problem is that the Cinnamon mixer applet doesn't show my USB audio device in the list of selectable audio devices after I've connected it and turned it on UNTIL I select another existing internal audio device (my laptop has both a regular analogue audio and a HDMI output device built-in) to the one I'm currently using. Then, the next time I open the mixer applet I can see my USB audio device listed in the mixer menu and choose that as the active device but it doesn't show unless I switch output devices between the already displayed internal ALSA devices.

I'd imagine that if I didn't have two integrated ALSA devices then I'd need to reboot or at least kill and reload the mixer to get newly-attached USB audio devices to show. It's not ideal.

I'll provide any more details required to fix this bug, just let me know.

Thanks

**Comment by pixunil** [comment]
There is a PR #3858 outside which should fix that. You can test it and say if this fixes the bug for you.

Duplicate of #464.

**Comment by danboid** [comment]
Hi pixunil!

Its sounds like that PR should fix my problem but I'm pretty new to Github and I've been unable to work out how I clone and hence install it?

Thanks for your help!

**Comment by pixunil** [comment]
I'll give you some instructions how to download and install the applet:

```
cd /tmp
git clone https://github.com/pixunil/Cinnamon.git --branch sound-applet --single-branch
cp /tmp/Cinnamon/files/usr/share/cinnamon/applets/sound@cinnamon.org/ ~/.local/share/cinnamon/applets/
```

This will clone the git history for the `sound-applet` branch temporarily and will copy the sound applet into your applet directory.
Then, restart Cinnamon. (right click on the panel > Troubleshoot > Restart Cinnamon)
If you experience bugs or your issue is fixed, just make a post.

(The default sound applet is still on your disk, you can go into the directory `~/.local/share/cinnamon/applets/` and delete the folder `sound@cinnamon.org` to use the default one)

**Comment by danboid** [comment]
Thanks pixunil!

That sound applet PR has mainly fixed the prob for me in that my USB audio device now appears instantly in the list of output devices and it automatically switches to using it on connection which is the behaviour I want. 

The only (small) issue is that the dot that indicates the current output device doesn't move the new output device after its been attached and is being used for output. If I choose another device then switch back, the dot shows the correct device.

**Comment by pixunil** [comment]
Thank you for your feedback.

The auto-switching to the device shouldn't be the fault of the sound applet, as it only switches to a device when you click on the menu item - This should have happen also before, otherwise it would be very weird.

To the issue: I think I need some debugging info. Please add this line in `~/.local/share/cinnamon/applets/sound@cinnamon.org/applet.js`:

```diff
@@ -1424,6 +1424,7 @@ MyApplet.prototype = {
     },
 
     _onDefaultChanged: function(control, id, type){
+        global.log([control, id, type].join(", "));
         //go through the list of the Sources / Sinks and check if the ids are m
         for(let i = 0, l = this._streams.length; i < l; ++i){
             if(this._streams[i].type === type)

```

Then, restart Cinnamon and after connecting the USB device please make a screenshot of looking glass and post it here. (Troubleshoot > Looking Glass  and then select the Tab "Log")
Plus, I've got a question: Does another item has got the dot or no item?

**Comment by danboid** [comment]
No, it didn't auto-switch before. Before, under this version of Cinnamon (2.4.6) I used to briefly see a 'muted speaker' icon flash up in the middle of the screen when I attached a USB audio device. The behaviour I  have come to expect under GNOME/PA is for the output device to auto-switch to the latest attached device, as it does in the applet PR.

As for the dot, yes the dot is present on the integrated audio device, provided thats what I was last using, before I attach the USB device and it stays there after attaching the USB audio.

warning t=1970-01-01T01:00:00Z ================ DBus connection lost ===============
info t=1970-01-01T01:00:00Z ================ DBus connection established ===============
info t=2015-02-21T15:11:56Z loading user theme: /home/dan/.themes/Numix-Cinnamon/cinnamon/cinnamon.css
info t=2015-02-21T15:11:56Z added icon directory: /home/dan/.themes/Numix-Cinnamon/cinnamon/
info t=2015-02-21T15:11:56Z loaded at Sat Feb 21 2015 15:11:56 GMT+0000 (GMT)
info t=2015-02-21T15:11:56Z Loaded applet menu@cinnamon.org in 312 ms
info t=2015-02-21T15:11:56Z Loaded applet show-desktop@cinnamon.org in 3 ms
info t=2015-02-21T15:11:56Z Role locked: panellauncher
info t=2015-02-21T15:11:56Z Loaded applet panel-launchers@cinnamon.org in 26 ms
info t=2015-02-21T15:11:56Z Role locked: windowlist
info t=2015-02-21T15:11:56Z Loaded applet window-list@cinnamon.org in 5 ms
info t=2015-02-21T15:11:56Z Role locked: notifications
info t=2015-02-21T15:11:56Z Loaded applet notifications@cinnamon.org in 7 ms
info t=2015-02-21T15:11:56Z Loaded applet user@cinnamon.org in 14 ms
info t=2015-02-21T15:11:56Z Loaded applet removable-drives@cinnamon.org in 5 ms
info t=2015-02-21T15:11:56Z Loaded applet keyboard@cinnamon.org in 14 ms
info t=2015-02-21T15:11:56Z Loaded applet network@cinnamon.org in 42 ms
info t=2015-02-21T15:11:56Z Loaded applet sound@cinnamon.org in 25 ms
info t=2015-02-21T15:11:56Z Loaded applet power@cinnamon.org in 8 ms
info t=2015-02-21T15:11:56Z Loaded applet systray@cinnamon.org in 4 ms
info t=2015-02-21T15:11:56Z Loaded applet calendar@cinnamon.org in 11 ms
info t=2015-02-21T15:11:56Z Loaded applet windows-quick-list@cinnamon.org in 4 ms
info t=2015-02-21T15:11:56Z Loaded applet workspace-switcher@cinnamon.org in 5 ms
info t=2015-02-21T15:11:56Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 4294967295, Source
info t=2015-02-21T15:11:56Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 2, Sink
info t=2015-02-21T15:11:56Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 3, Source
info t=2015-02-21T15:11:56Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 2, Sink
info t=2015-02-21T15:11:56Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 3, Source
info t=2015-02-21T15:11:57Z Adding systray: parcellite (20x20px)
info t=2015-02-21T15:11:57Z    Resized parcellite (23.200000762939453x23.200000762939453px)
info t=2015-02-21T15:12:43Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 2, Sink
info t=2015-02-21T15:12:43Z [object instance proxy GIName:Gvc.MixerControl jsobj@0x7f3fc44145e0 native@0x44fab00], 3, Source

**Comment by pixunil** [comment]
What are the sound settings thinking about it? Is the USB device present and selected or your integrated one?
If it does not there, there could to be a problem with gvc, as it doesn't report the switching (this is what I read from your log).
And I currently have got no idea why those changes implies a auto-switching feature, even if it's good for you...

**Comment by danboid** [comment]
For that log, Cinnamon  was started with my USB audio unplugged and internal audio selected.

After the gvc events (ie plugging in the USB audio device), the PA output device would have switched to being USB audio but the dot in the applet output device menu remains next to  the internal audio device until I switch from it and back.

I'm not sure thats what you were asking?

**Comment by danboid** [comment]
I should note that I  had no sound producing apps running when I took that log if that makes a  difference?

**Comment by pixunil** [comment]
If you have apps that are producing sound or not, that should be irrelevant.
And just for clarification, this is what I mean with sound settings, it would be interesting how your USB device is handled there.
![](https://cloud.githubusercontent.com/assets/7093655/6318203/e6d2c06a-ba84-11e4-8546-2e5769a55d47.png)

Interesting for me would be these situations:

- open sound settings and then plug in the USB device
- plug in the USB device and then open sound settings

Questions for sound settings:
- Does the USB device show up and is it selected?
- Does it auto-switch?

Questions for sound applet:
- after switching (auto or manually) to the USB device, does the volume slider on the sound applet work?
- does your machine auto-switch to the USB device **without** the applet? (Just remove it from the panel and restart Cinnamon)

Thanks for your time.

**Comment by danboid** [comment]
open sound settings and then plug in the USB device

Plugging in my main USB audio device (a Philips Expanium portable hifi) when sound settings is open results in 2 new output devices appearing - they're the same except one is 'bass boost' mode and the other without. The Speaker/Built-in audio remains the active selection under the settings window. However, if I play a video under Firefox, the audio is output via the just inserted USB device.


    plug in the USB device and then open sound settings

No difference. Three output devices are shown, Speaker/Built-in audio is the selected one even though the audio is being output via one of the USB devices.

Questions for sound settings:

    Does the USB device show up and is it selected?

Yes it shows up as 2 devices but the internal audio remains selected / highlighted as being the active device when its not.

    Does it auto-switch?

The audio does but the interface doesn't update appropriately.

Questions for sound applet:

    after switching (auto or manually) to the USB device, does the volume slider on the sound applet work?

The volume slider under the main applet menu only works when the internal audio device is active. It does not function for the USB device in bass boost or normal mode.

The output volume slider at the bottom of the sound settings window works for both internal and USB audio devices.

    does your machine auto-switch to the USB device without the applet? (Just remove it from the panel and restart Cinnamon)

No. After removing the mixer applet the sound output stops auto-switching when I connect my USB audio device.

Whilst performig these tests, I noticed another oddity with the mixer applet and the sound settings window. When I have my USB audio device plugged in, the applet output device sub-menu shows 3 devices:

Built-in Audio Digital Stereo (HDMI)
UAC 3553B Digital Stereo
Built-in Audio Analog Stereo

However, if I open the sound settings window whilst I still have the USB device connected I get to choose between the Built-in (analog) audio and the two different modes of the USB device. No HDMI option appears under the sound settings window.

With my USB device unplugged, I only see Built-in audio under the sound settings window but the output device menu shows:

Built-in Audio Digital Stereo (HDMI)
Built-in Audio Analog Stereo

[dan@arch76 ~]$ cat /proc/asound/cards 
 0 [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf7e14000 irq 33
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7e10000 irq 29
 2 [UAC3553B       ]: USB-Audio - UAC3553B
                      Philips UAC3553B at usb-0000:00:14.0-2, full speed
[dan@arch76 ~]$ cat /proc/asound/devices 
  2: [ 1]   : control
  3: [ 1- 0]: digital audio playback
  4: [ 1- 0]: digital audio capture
  5: [ 1- 2]: digital audio playback
  6: [ 1- 0]: hardware dependent
  7: [ 0]   : control
  8: [ 0- 3]: digital audio playback
  9: [ 0- 7]: digital audio playback
 10: [ 0- 8]: digital audio playback
 11: [ 0- 0]: hardware dependent
 12: [ 2]   : control
 13: [ 2- 0]: digital audio playback
 33:        : timer

**Comment by danboid** [comment]
[dan@arch76 ~]$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    PulseAudio Sound Server
default
    Default ALSA Output (currently PulseAudio Sound Server)
hdmi:CARD=HDMI,DEV=0
    HDA Intel HDMI, HDMI 0
    HDMI Audio Output
hdmi:CARD=HDMI,DEV=1
    HDA Intel HDMI, HDMI 1
    HDMI Audio Output
hdmi:CARD=HDMI,DEV=2
    HDA Intel HDMI, HDMI 2
    HDMI Audio Output
sysdefault:CARD=PCH
    HDA Intel PCH, VT1802 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    Front speakers
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, VT1802 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
sysdefault:CARD=UAC3553B
    UAC3553B, USB Audio
    Default Audio Device
front:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    Front speakers
surround21:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=UAC3553B,DEV=0
    UAC3553B, USB Audio
    IEC958 (S/PDIF) Digital Audio Output

**Comment by danboid** [comment]
I suppose the auto-switching of output device should be optional. I'd like to enable it if it isn't supposed to do that yet I can think if situations where people wouldn't want that to always switch output to the most recently attached - be that USB, HDMI, bluetooth or whatever.

**Comment by danboid** [comment]
I realise I reported a number of issues here but has any progress been made on fixing the probs?

**Comment by pixunil** [comment]
a228d6c5abcad286fd7b124962304ddc79e009ff
I pushed some little changes with debugging info and that should fix the problem with the volume.
It should gather some useful information `~/.cinnamon/glass.log`.
Can you please post the contents of it? (wrapped into [code blocks](https://help.github.com/articles/markdown-basics/#multiple-lines))
But as mentioned, I can't explain the auto-switch phenomena, hopefully it disappears.

**Comment by danboid** [comment]
Both volume sliders work for my USB audio device after I've manually selected it, but not after its auto-switched to it, which is still happening. I'm not sure I thought to check this with the previous version actually.

info t=2015-03-04T19:26:35.142Z loading user theme: /home/dan/.themes/Numix-Cinnamon/cinnamon/cinnamon.css
info t=2015-03-04T19:26:35.155Z added icon directory: /home/dan/.themes/Numix-Cinnamon/cinnamon/
info t=2015-03-04T19:26:35.225Z loaded at Wed Mar 04 2015 19:26:35 GMT+0000 (GMT)
info t=2015-03-04T19:26:35.621Z Loaded applet menu@cinnamon.org in 392 ms
info t=2015-03-04T19:26:35.627Z Loaded applet show-desktop@cinnamon.org in 5 ms
info t=2015-03-04T19:26:35.664Z Role locked: panellauncher
info t=2015-03-04T19:26:35.665Z Loaded applet panel-launchers@cinnamon.org in 37 ms
info t=2015-03-04T19:26:35.673Z Role locked: windowlist
info t=2015-03-04T19:26:35.674Z Loaded applet window-list@cinnamon.org in 8 ms
info t=2015-03-04T19:26:35.682Z Role locked: notifications
info t=2015-03-04T19:26:35.685Z Loaded applet notifications@cinnamon.org in 11 ms
info t=2015-03-04T19:26:35.707Z Loaded applet user@cinnamon.org in 21 ms
info t=2015-03-04T19:26:35.715Z Loaded applet removable-drives@cinnamon.org in 6 ms
info t=2015-03-04T19:26:35.737Z Loaded applet keyboard@cinnamon.org in 21 ms
info t=2015-03-04T19:26:35.784Z Loaded applet network@cinnamon.org in 46 ms
info t=2015-03-04T19:26:35.796Z Loaded applet power@cinnamon.org in 11 ms
info t=2015-03-04T19:26:35.803Z Loaded applet systray@cinnamon.org in 5 ms
info t=2015-03-04T19:26:35.821Z Loaded applet calendar@cinnamon.org in 16 ms
info t=2015-03-04T19:26:35.828Z Loaded applet windows-quick-list@cinnamon.org in 6 ms
info t=2015-03-04T19:26:35.836Z Loaded applet workspace-switcher@cinnamon.org in 7 ms
info t=2015-03-04T19:26:35.869Z Loaded applet sound@cinnamon.org in 32 ms
info t=2015-03-04T19:26:36.074Z adding stream 1 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a400 native@0x4068f60]
info t=2015-03-04T19:26:36.074Z adding stream 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:26:36.074Z _readOutput: 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:26:36.075Z adding stream 1 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a400 native@0x4068f60]
info t=2015-03-04T19:26:36.075Z Stream is a sink, the default one is 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:26:36.076Z adding stream 3 - [object instance proxy GIName:Gvc.MixerSource jsobj@0x7f5d1048a6a0 native@0x40688a0]
info t=2015-03-04T19:26:36.076Z adding stream 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:26:36.076Z Stream is a sink, the default one is 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:26:36.077Z adding stream 3 - [object instance proxy GIName:Gvc.MixerSource jsobj@0x7f5d1048a6a0 native@0x40688a0]
info t=2015-03-04T19:26:36.099Z _readOutput: 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:26:36.101Z adding stream 4 - [object instance proxy GIName:Gvc.MixerEventRole jsobj@0x7f5d1048abb0 native@0x48f38a0]
info t=2015-03-04T19:26:36.578Z Adding systray: parcellite (20x20px)
info t=2015-03-04T19:26:36.579Z    Resized parcellite (23.200000762939453x23.200000762939453px)
info t=2015-03-04T19:30:46.549Z adding stream 5 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d2fe57280 native@0x37c9c70]
info t=2015-03-04T19:30:46.554Z adding stream 6 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d2fe575e0 native@0x3831c60]
info t=2015-03-04T19:31:20.447Z _readOutput: 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:31:20.448Z adding stream 7 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d2fe93e20 native@0x34ba310]
info t=2015-03-04T19:31:20.448Z Stream is a sink, the default one is 2 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d1048a460 native@0x4068c60]
info t=2015-03-04T19:33:23.175Z adding stream 8 - [object instance proxy GIName:Gvc.MixerSourceOutput jsobj@0x7f5d2e3838b0 native@0x34ba190]
info t=2015-03-04T19:33:27.032Z adding stream 9 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d2e3c5610 native@0x49253a0]
info t=2015-03-04T19:33:28.425Z adding stream 10 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d2e3ec970 native@0x375aa40]
info t=2015-03-04T19:33:30.251Z adding stream 11 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d2e3fba90 native@0x2f8bd30]
info t=2015-03-04T19:33:32.438Z adding stream 12 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13d07130 native@0x34ba610]
info t=2015-03-04T19:33:33.823Z adding stream 13 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13d33a30 native@0x38a7df0]
info t=2015-03-04T19:33:35.007Z adding stream 14 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13d530d0 native@0x38eb170]
info t=2015-03-04T19:33:36.037Z adding stream 15 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13d69d00 native@0x4068d20]
info t=2015-03-04T19:33:37.040Z adding stream 16 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13d89c70 native@0x4925760]
info t=2015-03-04T19:33:38.224Z adding stream 17 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13da76d0 native@0x4068de0]
info t=2015-03-04T19:33:39.284Z adding stream 18 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13dbaa00 native@0x3831960]
info t=2015-03-04T19:33:40.242Z adding stream 19 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13de3a30 native@0x4925160]
info t=2015-03-04T19:33:41.182Z adding stream 20 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13df7460 native@0x49252e0]
info t=2015-03-04T19:33:42.157Z adding stream 21 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13f1b2b0 native@0x34ba490]
info t=2015-03-04T19:33:45.497Z adding stream 22 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13f2cf40 native@0x4068ea0]
info t=2015-03-04T19:33:51.288Z _readOutput: 7 - [object instance proxy GIName:Gvc.MixerSink jsobj@0x7f5d2fe93e20 native@0x34ba310]
info t=2015-03-04T19:33:56.276Z adding stream 23 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13f5a670 native@0x4925520]
info t=2015-03-04T19:33:58.381Z adding stream 24 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13f81550 native@0x48f3a20]
info t=2015-03-04T19:33:59.552Z adding stream 25 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13f90e20 native@0x48f3ae0]
info t=2015-03-04T19:34:00.761Z adding stream 26 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13fa4550 native@0x38a7af0]
info t=2015-03-04T19:34:03.326Z adding stream 27 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13fa4c40 native@0x48f3ba0]
info t=2015-03-04T19:34:09.218Z adding stream 28 - [object instance proxy GIName:Gvc.MixerSinkInput jsobj@0x7f5d13ff59a0 native@0x48f3960]

**Comment by pixunil** [comment]
I hope fb4284dc5b1cbc3e3222124b729c0889fedf0241 fixes the unwanted auto-switching.
I assume that somehow the backend (pulse audio) switches, but gvc (the thing between the applet and pa) doesn't get the change, so the change is a bit "hacky".

**Comment by danboid** [comment]
Yep, auto-switching has stopped. I  actually liked that but I understand it wasn't supposed to happen :)

There is still the issue of the applet Output device menu and sound settings window showing a different selection of devices though.

**Comment by artscoop** [comment]
@pixunil, the last fix you submitted changed the UI in a good way, and fixed everything, this is just perfection. Thanks.

**Comment by darkMatterSound** [comment]
Hey, @pixunil.  It looks like you moved the sound applet?  I'm getting this:

warning: Could not find remote branch sound-applet to clone.
fatal: Remote branch sound-applet not found in upstream origin
Unexpected end of command stream

Where can I find the fix now?

**Comment by pixunil** [comment]
@darkMatterSound, i deleted the branch as it is merged into master. You can find the fix in this repository or in [nightly](https://github.com/linuxmint/Cinnamon/wiki/Trying-out-the-latest-Cinnamon-without-building-it.).

Guess, this can be closed.

**Comment by darkMatterSound** [comment]
@pixunil, Hrm, I installed the newest nightly but it doesn't seem to resolve my audio interface issue.  I still have to restart before Mint will recognize it.  Maybe it's my particular interface?

**Comment by pixunil** [comment]
First, I hope you did a restart of Cinnamon…

When it still doesn't work, then it should be a bug with the sound backend **G**nome **V**olume **C**control (or pulse audio, but I'm not sure).
To be sure, look into the sound module of cinnamon settings. If it updates there, but not in the sound applet, it is still a problem of the sound applet.

**Comment by darkMatterSound** [comment]
Oh, but of course I restarted Cinnamon, lol!  It doesn't update in either spot.  The sound module or the applet.  Whatever's in the module is always reflected on the applet on my system.

It's not a huge issue here.  I just have to do a pulseaudio -k && alsa force-reload and then a pulseaudio and then it refreshes all my devices.  But still not hot-swappable yet on this end.

**Comment by ManIVIctorious** [comment]
The cinnamon sound settings have seen a lot of work recently, does this issue still occur in cinnamon 3.0?

**Comment by artscoop** [comment]
I've not been bugged by this for a long time. Seems this was fixed in March/May 2015.
Another bug was raised recently with sound input selection doing nothing, but it was fixed in August 2016.

**Comment by JosephMcc** [comment]
I'd like to know if the OP is still having this issue.

**Comment by danboid** [comment]
Hi Joseph!

I'll test this tonight and get back to you later. I don't swap between audio devices as much as I used to these days because my main amp at home doesn't have USB input.

**Comment by danboid** [comment]
Hi JosephMcc

Just tried switching audio outputs from internal to USB under Mint 18 / Cinnamon 3.0.7 and it is working as it should.

Thanks!
