### ISSUE TITLE
Modal dialogs and focus

### ISSUE THREAD

**Issue by lestcape** [linuxmint/Cinnamon#4406]
When i have a menu open and the menu invoke a modal dialog, the modal dialog require a focus and the popup menu manager will invoke the menu close. This is in my opinion wrong, as i want to see all in the same way when i return to the normal state (i.e. close the modal dialog). i think will be useful intercept the focus change and block the signal if is it belongs to an actor that was pushed on modal.

**Comment by JosephMcc** [comment]
Just to be sure I understand correctly I'm using the trash applet as an example. If I right click the applet and choose "Empty trash" the menu closes and the confirmation dialog opens. In this situation you want the menu to remain open? If so I have to disagree with you. I would find it staying open to be strange behavior. I can't think of anywhere else offhand that it works like this. In any instance I can think of choosing a menu option that opens a dialog closes the menu.

**Comment by lestcape** [comment]
@JosephMcc true, in the conception of this specific task, but in general the menu of the applets not needed to be launchers or process invokers. So, in the case that you are doing something that will require a confirmation but for continue the task inside the menu... Thats will be the problem...

**Comment by collinss** [comment]
@lestcape I agree with @JosephMcc. In the majority of cases, I would expect the menu to close if I click on an item. If you have a specific instance where you don't want this to happen, you can always override the ```activate``` *method* of the menu item instead of connecting to the ```activate``` *signal*. This ensures that the signal doesn't propagate through the menu chain and trigger a close of the menu.

**Comment by lestcape** [comment]
@collinss i also agree with @JosephMcc and what i was talking is about the modal dialog and the popupmenu manager, no about items... I have not access and i can not filter events on global, because the menu global event is connected first than my attempt. What i try to do also involved your code (this is an equivalent of your Raise Box), but to inhibit events when i select a color.

**Comment by lestcape** [comment]
I will say this in other way... I want to have an option to inhibit the events of the popup menu manager (that occurs in global): https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L2175-L2179

**Comment by collinss** [comment]
@lestcape I did something kind of like that with my sticky notes applet: https://github.com/collinss/Cinnamon-Sticky-Notes/commit/dcc0c381b37abf48e1dbc943f5b472e165834877

**Comment by lestcape** [comment]
Yes @collinss, but what i try to do is more like an api, not for a particular applet... Is port the cinnamon settings inside the applets with a cinnamon extension or something... see, the idea here: https://github.com/linuxmint/Cinnamon/issues/4403

**Comment by lestcape** [comment]
@collinss anyway, after see better your code and adapt it to my idea. I suppose that i can explored where i'm, go to the parent and then to the delegate and ask if it's a popup menu then override the function  _shouldBlockEvent https://github.com/collinss/Cinnamon-Sticky-Notes/commit/dcc0c381b37abf48e1dbc943f5b472e165834877#diff-7303310396e810f08fa2a6710ff0e9ebR241 injecting a code dynamically to prevent the applet manager to close the menu, and return the original code to the function when the RiseBox will be closed.  This will work, but really this is a crude hack!!

**Comment by lestcape** [comment]
As opposite, what i request can be satisfy easy... in main.js

put a flag: inibitMenuManagerEvents = false;

then ask for the value of this flag in the capture event of the menu manager if is true return with false, to be handled for extension who set this state...

Here:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/popupMenu.js#L2375

Change:
```
 } else if (!this._shouldBlockEvent(event)) {
```

For this:
```
 } else if (!this._shouldBlockEvent(event) || Main.inibitMenuManagerEvents) {
```

**Comment by lestcape** [comment]
Just a reference, of difference types of event handles and why i can not filter the event in a properly way:
http://www.quirksmode.org/js/events_order.html

**Comment by lestcape** [comment]
Another more general idea will be add a reference to a manager of popup Menu Manager in main, to iterate over all menuManagers, then open and close the menu that we want, disconnect or connect signals and more....

**Comment by lestcape** [comment]
This is how i finally can do what i want, without know where the actor is:

1- Find the top menu:
https://github.com/lestcape/Color-Chooser/blob/master/colorChooser%40lestcape/colorChooser.js#L967

2- Override Menu Source Actor Contains:
https://github.com/lestcape/Color-Chooser/blob/master/colorChooser%40lestcape/colorChooser.js#L955-L956

Thanks for the suggestion.

**Comment by ManIVIctorious** [comment]
@lestcape does this mean your request is resolved or should the issue stay open?

**Comment by lestcape** [comment]
@ManIVIctorious This is not resolved, but don't appear that will be solved if the solution is hacking the code, and this is the direction in this thread... Will not help to change anything in cinnamon in this way, so can be closed.
