### ISSUE TITLE
Can't disable animations for expo/scale in Cinnamon Settings

### ISSUE THREAD

**Issue by M4he** [linuxmint/Cinnamon#446]
For low spec hardware like netbooks it is very useful that you can turn off window and workspace switching animations within the cinnamon settings.

I think it would be nice to toggle the animations within expo and overview as well because the zooming animation is quite heavy. However this would bring up some things that would need to be discussed first:
1. should the "Enable desktop effects"-switch in the settings be used for expo and overview as well or would it be better to introduce seperate switches?
2. if turning off animations, should expo and overview have no animation at all or should it just be reduced to a simple fade animation?
3. or should the user even be able to select each animation seperately like for the window effects (i.e. for expo enter animation choose between "Zoom" or "Fade") ?

I'm looking forward to hear your opinions on this!

**Comment by phocean** [comment]
I found this issue, desperately looking for a way to disable these animations.

**Comment by mifas** [comment]
@phocean try this

1. Edit this file
   `sudo xed /usr/share/cinnamon/js/ui/expo.js`

2. Change const ANIMATION_TIME - (Do not set to 0, then it will cause some issues)
`const ANIMATION_TIME = 0.1;`

3. Save and Reboot

**Comment by germanfr** [comment]
This can be closed, it's already fixed in the latest version.

**Comment by JosephMcc** [comment]
@germanfr Where is this fixed? Changing the effects setting doesn't seem to effect expo in any way. 

As for the suggestions on how to do this, the animation settings need to be simplified. We have a lot of code for handling this. There should be a single switch at the very least that disables all animations completely. From what I've seen the majority of users who want to change the defaults, simply want them off entirely.

**Comment by germanfr** [comment]
Yes, sorry my bad @JosephMcc. This is fixed in scale only, not in expo.

Regarding that switch, it already exists. There is an option in effects to disable window animations which is used by scale to turn them off.

**Comment by olfek** [comment]
I want this too.

> There is an option in effects to disable window animations which is used by scale to turn them off.

@germanfr This **only** disables window animations. Not **expo** animations.

@mifas Your suggestion still shows animation, it has just increased the speed of it.

**Comment by bardiarajabi** [comment]
Opened in Feb 29, 2012 and still this issue is open...
