### ISSUE TITLE
Cinnamon Menu applet not showing newly-installed programs

### ISSUE THREAD

**Issue by linuxbeak** [linuxmint/Cinnamon#4498]
I've noticed a minor issue with the menu applet in Cinnamon 2.6.13, where the menus are not being updated after a new application is installed. The only way I've found to get the apps to show up is by logging out and logging back in or typing cinnamon --replace in the command line. Perhaps this is an Arch specific issue, so I was wondering if anyone else could reproduce this.

Version: 2.6.13
Distro:Arch Linux
Steps to recreate:
Install software such as firefox or chromium and look at the menu. If the bug is reproduced, it should not show the newly-installed software either in the menu or in the search function.

**Comment by tgharib** [comment]
I noticed the same bug too. I noticed that same bug when I was running Unity on Arch. I thought I was going insane.

**Comment by linuxbeak** [comment]
I just noticed that it only occurs with certain programs. For instance, it occurs when I install Chromium, but not Gthumb. Maybe it has something to do with the way the .desktop files are being read.

**Comment by linuxbeak** [comment]
This is strange. If I manually move the chromium.desktop file out of /usr/share/applications and put it back, the menu entry properly disappears and reappears. However, if I uninstall and reinstall chromium, the icon does not reappear until I restart cinnamon.

**Comment by SirCmpwn** [comment]
:+1:, still an issue

**Comment by keitalbame** [comment]
Same here. It happened with blueman (Bluetooth Manager). After copy paste Bluetooth Manager file on /usr/share/applications/, the icon reappears on menu.

Either during install or update, which is anoying, the need to reboot for the icons reapper. Now I know this workaround.

This happens in some applications. I will try to pin point them as I'm detecting them.
Chromium and Blueman for sure.

I'm on Arch.

**Comment by JosephMcc** [comment]
Confirmed. I reproduced this installing the Atom text editor.

**Comment by real-or-random** [comment]
Downstream says that the same bug has been fixed in gnome:
https://bugs.archlinux.org/task/45992

**Comment by bemeurer** [comment]
Having this as well.

**Comment by mtwebster** [comment]
Fixed by: https://github.com/linuxmint/cinnamon-menus/compare/5b8c9026e3269fb91d178c3985c11f9ac1e2afda...44ee2de737e53b0d1f59df46fc2df8ed1b5ea5ff

**Comment by ranchoiver** [comment]
Still reproduces? 

Distro: OpenSuse 42.2
Version: 3.2.8
Steps to recreate: 

Install this app using rpm package.
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-
It doesn't appear in menu until Cinnamon restart.
