### ISSUE TITLE
update notifier does show update icon even no update is available

### ISSUE THREAD

**Issue by Hanmac** [linuxmint/Cinnamon#4702]
i don't know if its a bug on cinnamon but the update notifier does even show a black icon, even no update is available ... 
normally it shouldn't show any icon, but i cant deactivate that without killing the update notifier process.

**Comment by pixunil** [comment]
I think you mean [mintupdate](https://github.com/linuxmint/mintupdate), not Cinnamon.
Check the settings (_Right click on the icon_ > Settings), there should be one to hide it if you are up-to-date.

**Comment by Hanmac** [comment]
no on this machine, mint stuff is not installed. Cinnamon comes over ppa (nightly).

update-notifier is the process, (hm i am unsure if its a cinnamon bug and not a bug in update-notifier itself)
it does show in the systray as a black sun symbol (a black version of the normally orange one)
when i ask it, it says no updates available, but it does not disappear

right click on the icon does not work because its the systray applet, left click does show Settings, but there are none there i might hide the icon (they are the system update settings)

hm for unknown reason i cant reproduce it on my second system, but i might test that later.

hm the update-notifier is not the only thing that does show an icon in the systray even if the options does say it should not. (vino does that too)

**Comment by lestcape** [comment]
Maybe, this was solved here: https://github.com/linuxmint/Cinnamon/commit/f9d985753639e1be9ca6709255395467dad3f3d2

**Comment by Hanmac** [comment]
hm I tried with newest nightly version (that does have this change apply) but my problem is not solved.

if i have the "update-notifier" process running and then i restart cinnamon (it also does work when I just login)
then the icons from update-notifier and from vino server are shown even if their options does say that they should not show icons.
(if i does set "never" show icon in the vino settings it still does show the icon when cinnamon got restarted.)

**Comment by lestcape** [comment]
@Hanmac this is interesting, because to show an icon, the app need to send a message to the cinnamon Dbus notifier. I will try to find what happens. Probably is because the application inform the icon state in some different message and is not currently capture.

**Comment by lestcape** [comment]
Well at last i have the time to see what happend.

Please see this:
https://bugs.launchpad.net/ubuntu/+source/update-notifier/+bug/1246364

What occurs is this: The original  extension for gnome shell omitted the passive state of the appindicators.
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L46

Read here what mean a passive state:
http://api.kde.org/4.8-api/kdelibs-apidocs/kdeui/html/classKStatusNotifierItem.html#a5a724a726f39f52275ee62e1fe2ff539

When know about this problem, I created a method to take in account the passive state:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L853

The problem is that i forget call the _updatedStatus in the initialization of an icon of appindicator, so currently will not be taking into account the current  state of the appindicator "status" as will only be executed the method after capture the status signals.

This can be easy fixed adding a call to _updatedStatus before this line:
https://github.com/linuxmint/Cinnamon/blob/master/js/ui/indicatorManager.js#L1026

But please see: In ubuntu the status-notifier always will have the passive state, and will never be shown, so if i add this called, we never will see the update-notifier in the panel and we never can access to his menu ofcourse.

Then i want to know what will be the decision here, to apply the patch.

Regards.

**Comment by Hanmac** [comment]
hm ok that is interesting, but somehow it has been working before, now it did break on cinnamon a few weeks ago

it has been working on my pc because i didn't restart cinnamon, but from my uptime i might guess when it still did work

its confusing because the launchpad bug is years ago and cinnamon wasn't affected yet

**Comment by lestcape** [comment]
If you say Mint wasn't affected yet, you probably have right. This is related with the ubuntu update-notifier. I use ubuntu. Remember Mint have a different way of Ubuntu to handle the updates, but i don't know how Mint handled the passive mode, because is a characteristic of indicators and this is a new feature in cinnamon, so probably the mint update notifier need a change to support better this characteristics. I don't know.

**Comment by Hanmac** [comment]
Sorry if I did confuse you
I use Ubuntu with cinnamon nightly repository too

**Comment by lestcape** [comment]
I'm also handle a repo of cinnamon in ubuntu 14.04 and I've never seen the update-notifier working in ubuntu (with cinnamon and with the standard one) before the support of appindicator, so i don't know what you mean or if you do something special.

**Comment by Hanmac** [comment]
hm i think i remember that it did work a few months before, (before 15.10)
now i think it did work recently with my system too (my system got booted 22 days ago)
then yesterday i restart cinnamon, and now it is broken at home too

===

at work its currently broken: 
today i login and i got the black icon with saying " 0 updates available"
then i did apt-get update myself, and the icon got red with saying "46 updates available"
after installing the icon didn't got back to black and does still say "46 updates available"

but it also happens that the black icon did appear and saying that updates available,
even if they might be already installed.

**Comment by lestcape** [comment]
I only can speak about Ubuntu 14.04, if is other version, i don't know what can occur. Clear i don't invented the update-notifier bug in launchpad, so what is pretty clear is that: no one can ensure that this will work ok with all active ubuntu versions. I think what is more important here is the mint decision about how they want handle the passive mode. With other distros (specially ubuntu, although this particularly hurts me) we cannot ensure anything.

**Comment by solivan07** [comment]
Also using Ubuntu 14.04 with cinnamon nightly repository. This worked for me : 
> Go to system settings then general. Make sure "Enable support for indicators" is off. Restart cinnamon.

found here:
[https://www.reddit.com/r/linux4noobs/comments/3y6fol/keepassx_icon_in_the_tray_doesnt_work_properly/cyaxl9l](url)

Hope this helps.

**Comment by JosephMcc** [comment]
@lestcape you are familiar with running Cinnamon under Ubuntu and the use of the indicators in the systray. Is this a bug in our systray implementation or an issue on the Ubuntu side of things?

**Comment by lestcape** [comment]
@JosephMcc this is a bug in the ubuntu side, and also this could be interpreted as a bug in the cinnamon indicator side. There are not a clear procedure of what we can do with the passive state. In ubuntu, the passive state mean don't show the indicator icon and as a result all bugs related with the passive state are not displayed to the user. Actually, the indicator implementation of Cinnamon show the indicator icon and then we can see a wrong icon if we use a client like the ubuntu update manager.

**Comment by lestcape** [comment]
@JosephMcc I add an option to show the icons on a passive state or not as a user preference in settings if you have ubuntu, you can see what happen: https://github.com/lestcape/Systray-Indicator

**Comment by Vahan86** [comment]
@Hanmac, does this issue still relevant to Cinnamon 3.6?
