### ISSUE TITLE
Cinnamon crash on Chrome DevTool moving DOM elements via drag'n'drop

### ISSUE THREAD

**Issue by ipxwork** [linuxmint/Cinnamon#4789]
In Chrome developer tools, Elements tab if drag and drop document nodes to change position in dom, cinnamon crash (on dragged elements and nearly is visible some black artifacts) and start run in fallback mode, appear dialog and ask if want to restart cinnamon

i used blackport and romeo repositories
linux mint 17.2 x64 (3.16.0-38-generic)
Cinnamon 2.8.2
Chrome 48.0.2552.0 dev (64-bit)
additonal:
i have connected 2 monitors (same model) with one panel on each and "window list for multi monitors" applet

**Comment by t57ser** [comment]
+1

**Comment by entr** [comment]
+1

**Comment by lDucks** [comment]
+1

**Comment by postbud** [comment]
+1, after latest update.
Version 48.0.2564.82 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)

**Comment by pierrre** [comment]
Same issue with Gnome Shell 3.18.3.
Is it a Chrome or a GTK bug?

**Comment by sercanarici** [comment]
+1

**Comment by nickcolley** [comment]
Same problem with Fedora Gnome Shell 3

**Comment by bra1n** [comment]
This is horrible. +1

**Comment by mtwebster** [comment]
I can't reproduce this.. If i open the dev panel, I can grab the `...` area in front of an element, and reposition it in the list without any crash.  Chrome 48.0.2564.103

However, I'm also running the latest cinnamon off github, not what's currently in release.  I will try with release packages.

**Comment by nickcolley** [comment]
I just reproduced it and got the following logs from journalctl

```bash
Feb 09 15:52:09 DRP-001964 gnome-session[2437]: (gnome-shell:25436): Cogl-ERROR **: Failed to create texture 2d due to size/format constraints
Feb 09 15:52:10 DRP-001964 gnome-session[2437]: WARNING: Application 'gnome-shell.desktop' killed by signal 5
Feb 09 15:52:10 DRP-001964 gnome-session[2437]: gnome-session[2437]: WARNING: Application 'gnome-shell.desktop' killed by signal 5
Feb 09 15:52:12 DRP-001964 gnome-session[2437]: current session already has an ibus-daemon.
Feb 09 15:52:13 DRP-001964 gnome-session[2437]: abrt-applet: repeated problem in gnome-shell-3.14.4-2.fc21, not showing the notification
Feb 09 15:52:13 DRP-001964 gnome-session[2437]: ** (gnome-shell:25944): CRITICAL **: nma_mobile_providers_database_lookup_cdma_sid: assertion 'sid > 0' failed
Feb 09 15:52:14 DRP-001964 gnome-session[2437]: GNOME Shell started at Tue Feb 09 2016 15:52:13 GMT+0000 (GMT)
```

**Comment by mtwebster** [comment]
To the people running Cinnamon, if you look at the start of your log, look for a line saying NPOT sizes allowed or not allowed, please tell me what you see.

This is an issue with clutter, which both shell and cinnamon use, but Cinnamon tries to avoid the issue in certain cases.

**Comment by entr** [comment]
Would if I could find the log! Where is it supposed to be in Mint?

**Comment by mtwebster** [comment]
Sorry - `~/.xsession-errors` in mint or ubuntu

**Comment by entr** [comment]
```term
$ less ~/.xsession-errors | grep -i npot
St-Message: cogl npot texture sizes SUPPORTED
```

I'm `tail`ing and start a drag(in chrome dev tools).
```log
$ tail -f ~/.xsession-errors 
Window manager warning: Log level 16: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
nm-applet-Message: moving back from GtkStatusIcon to indicator
Cjs-Message: JS LOG: network applet: Found connection for active

** (nvidia-prime:18377): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
[18800:18830:0209/194359:ERROR:upload_data_presenter.cc(74)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)
[18800:18830:0209/194359:ERROR:upload_data_presenter.cc(74)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader &)
Created new window in existing browser session.

(cinnamon:19149): St-WARNING **: Ignoring length property that isn't a number

(cinnamon:19149): Cogl-ERROR **: Failed to create texture 2d due to size/format constraints

** (gnome-terminal:18500): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (nm-applet:18384): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (nemo:18386): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (nvidia-prime:18377): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
[WARN 19:42:02.439684] [Environment:161] XDG_SESSION_CLASS not set in this environment!
[WARN 19:42:02.439730] [Environment:192] XDG_SESSION_TYPE not set in this environment!
[WARN 19:42:02.462779] [Gtk] Theme parsing error: gtk-widgets.css:997:2: Missing name of pseudo-class
[WARN 19:42:02.510127] [Preferences:192] '/usr/share/plank/themes/Default/dock.theme' is read-only!
[WARN 19:42:02.510381] [Preferences:384] Missing key 'CascadeHide' for group 'PlankDockTheme' in preferences file '/usr/share/plank/themes/Default/dock.theme' - using default value
[WARN 19:42:02.633927] [Matcher:124] plank_matcher_active_launchers: runtime check failed: (_tmp3_ != NULL)
[CRITICAL 19:42:03.469967] [DockWindow:290] Retry #1 update_size_and_position() to force requested values!
[CRITICAL 19:42:03.470314] [DockWindow:290] Retry #2 update_size_and_position() to force requested values!
[WARN 19:43:35.379097] Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
[CRITICAL 19:43:35.379985] [DockWindow:290] Retry #1 update_size_and_position() to force requested values!
[WARN 19:43:35.419387] [WindowControl:79] Window-manager changed: Metacity
[WARN 19:43:35.444213] Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
[WARN 19:43:55.631965] Failed to fetch xids: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/0x282a980
[WARN 19:43:55.632059] [WindowControl:147] plank_window_control_get_num_windows: runtime check failed: (_tmp2_ != NULL)
[WARN 19:43:55.663252] Failed to fetch xids: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/2088512325
[WARN 19:43:55.663342] [WindowControl:223] plank_window_control_update_icon_regions: runtime check failed: (_tmp2_ != NULL)
[WARN 19:43:55.690366] Failed to fetch xids: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/2088512325
[WARN 19:43:55.690452] [WindowControl:223] plank_window_control_update_icon_regions: runtime check failed: (_tmp2_ != NULL)
[WARN 19:43:55.716940] Failed to fetch xids: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/2088512325
[WARN 19:43:55.717030] [WindowControl:147] plank_window_control_get_num_windows: runtime check failed: (_tmp2_ != NULL)
[CRITICAL 19:43:55.717886] [DockWindow:290] Retry #1 update_size_and_position() to force requested values!
[WARN 19:43:55.723282] Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
[WARN 19:43:55.728076] Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
[WARN 19:43:55.729304] [WindowControl:79] Window-manager changed: Mutter (Muffin)
[CRITICAL 19:43:56.664133] [DockWindow:290] Retry #2 update_size_and_position() to force requested values!
[WARN 19:43:56.694952] [PositionManager:797] Without a draw_value there is trouble ahead for 'zlatev@zlatev-ThinkPad: ~'
[WARN 19:43:56.695569] [PositionManager:797] Without a draw_value there is trouble ahead for 'zlatev@zlatev-ThinkPad: ~'
[CRITICAL 19:43:56.710715] [DockWindow:290] Retry #1 update_size_and_position() to force requested values!
[CRITICAL 19:43:56.710819] [DockWindow:290] Retry #2 update_size_and_position() to force requested values!
[WARN 19:48:07.357217] Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallba
** (cinnamon-launcher:18355): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (gnome-panel:19487): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

(gnome-panel:19487): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:997:2: Missing name of pseudo-class

** (gnome-terminal:18500): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (cinnamon-launcher:18355): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (nemo:18386): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
nm-applet-Message: using fallback from indicator to GtkStatusIcon

** (nm-applet:18384): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (gnome-panel:19487): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug

*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug


** (cinnamon-launcher:18355): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (cinnamon-launcher:18355): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

(cinnamon-launcher:18355): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:997:2: Missing name of pseudo-class

** (cinnamon:19499): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

** (cinnamon:19499): WARNING **: Can't load fallback CSS resource: Failed to import: The resource at '/org/gnome/adwaita/gtk-fallback.css' does not exist

(cinnamon:19499): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:997:2: Missing name of pseudo-class
Panel leaving: a new panel shell is starting.

(gnome-panel:19487): EggSMClient-CRITICAL **: egg_sm_client_set_mode: assertion 'global_client == NULL || global_client_mode == EGG_SM_CLIENT_MODE_DISABLED' failed

```

Hope that helps.

**Comment by mtwebster** [comment]
Are we all talking about the dev panel that comes up in chrome when you hit F12?  Or is there some other, standalone tools?  I'm sorry if it sounds like a dumb question - I just want to be sure I'm trying to reproduce the same thing.

**Comment by entr** [comment]
Yes, that one. I can confirm this happens also in latest Opera (also
chromium based I guess) on 2 different machines Mint 17.3

**Comment by mtwebster** [comment]
I'd like to catch some debugging info on this if possible from affected users (in Cinnamon) -

The following will install necessary debug packages, as well as a small script that automates information-gathering for us to a degree.

sudo apt-get install cinnamon-dbg (if you're on non-dpkg-based system, hopefully there's a meta-package you can install that draws in all debug symbols for our common libraries)
wget https://raw.githubusercontent.com/linuxmint/Cinnamon/master/utils/cin-debug
chmod a+x ./cin-debug
What cin-debug does is attaches a debugger to a process, waits until it crashes, then gets a back trace, saving all of this to a file in your home folder.

the usage is (with cinnamon already running):
./cin-debug cinnamon &

This will request your sudo password (required for attaching to a running process). The & (ampersand) will allow the process to run in the background - you can omit this or not - it shouldn't affect the results.

The resulting log file should end up in your home folder as cinnamon-xxxx.log with a time/date stamp. Paste that to dpaste.com or pastebin.com and link it here.

Once you're done with the tool, I'd recommend a reboot (it makes zombies occasionally).

Thanks!

**Comment by entr** [comment]
http://pastebin.com/QRgX1TZY

**Comment by mtwebster** [comment]
Thanks

Interesting development.. I can reproduce this on my intel graphics laptop, but not on my nvidia desktop.

Can you guys report what graphics card and driver you're running on, as well as what mesa version you have? (`dpkg -s libegl1-mesa` works)

I reproduced on 10.1.3-0ubuntu0.6, i'm building the previous version to compare against.

**Comment by ipxwork** [comment]
this is on work pc
```
$ lshw -C video
  *-display               
       description: VGA compatible controller
       product: 2nd Generation Core Processor Family Integrated Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:27 memory:fe000000-fe3fffff memory:c0000000-cfffffff ioport:f000(size=64)
```
at home i have laptop with integrated intel card and nvidia as extended, same bug exist

**Comment by entr** [comment]
Yes, optimus laptop using intel's gpu.

```teminal
$ dpkg -s libegl1-mesa-lts-vivid:amd64 
Package: libegl1-mesa-lts-vivid
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 272
Maintainer: Ubuntu X-SWAT <ubuntu-x@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: mesa-lts-vivid
Version: 10.5.9-2ubuntu1~trusty2
Replaces: libegl1-mesa, libegl1-x11
Provides: libegl1-mesa, libegl1-mesa-drivers, libegl1-x11, xorg-renamed-package, xorg-renamed-package-lts-vivid
Depends: libc6 (>= 2.14), libdrm2 (>= 2.4.25), libexpat1 (>= 2.0.1), libgbm1-lts-vivid (>= 7.11~1), libwayland-client0 (>= 1.3.92), libwayland-server0 (>= 1.2.0), libx11-xcb1, libxcb-dri2-0 (>= 1.8), libxcb-xfixes0, libxcb1, libudev1, libgl1-mesa-dri-lts-vivid (= 10.5.9-2ubuntu1~trusty2)
Pre-Depends: multiarch-support
Conflicts: libegl1-mesa, libegl1-x11, xorg-renamed-package-lts-utopic
Description: free implementation of the EGL API -- runtime
 This package contains the EGL native platform graphics interface library.
 EGL provides a platform-agnostic mechanism for creating rendering surfaces
 for use with other graphics libraries, such as OpenGL|ES.
 .
 This package contains modules to interface with the existing system GLX or
 DRI2 drivers to provide OpenGL via EGL.
Homepage: http://mesa3d.sourceforge.net/
Original-Maintainer: Debian X Strike Force <debian-x@lists.debian.org>

```

Is that normal?

**Comment by mtwebster** [comment]
Good news - I've more or less determined what's causing the problem.  I'm fairly certain it's chrome at fault, but not 100% - 

I noticed on my workstation, which is running nvidia hardware (not experiencing this bug), and has two monitors, when I drag an item, the 'shadow' or highlight extends to the right to infinity.  If the browser is in the left monitor, the highlight extends off the edge of the right-hand monitor.

So I check in our code, where this chain of events begins, and when I attempt to drag an item, it's requesting of our compositor a 21,052 (pixels) wide x 52 tall texture - way out of bounds it would seem.  I'm hoping to put in some sane limit in our code to clamp the size requests to, perhaps, the maximum (x server) screen size in each direction.

I'll try to get it tested and maybe have a few test packages here to try in a couple hours.

Maybe someone a bit more familiar with the chromium/chrome project could see if there is any mention of this issue on their bug trackers?

As for why it seems to affect Intel and not NVidia, I've no idea how it works down there, it could be some limit on how many pixels per 'row' or some such, that one handles better than the other.  It can't be pure pixel count, since the offending count is relatively small compared to a modern hi-dpi monitor or multi-monitor setup.

**Comment by mtwebster** [comment]
#### 64-bit Packages

https://dl.dropboxusercontent.com/u/8201170/muffin/64bit-cogl-fixed/gir1.2-muffin-3.0_2.8.4_amd64.deb
https://dl.dropboxusercontent.com/u/8201170/muffin/64bit-cogl-fixed/libmuffin0_2.8.4_amd64.deb
https://dl.dropboxusercontent.com/u/8201170/muffin/64bit-cogl-fixed/muffin-common_2.8.4_all.deb
https://dl.dropboxusercontent.com/u/8201170/muffin/64bit-cogl-fixed/muffin-dbg_2.8.4_amd64.deb

This seems to prevent the crash pretty reliably on our end.  I'm still pretty certain this is something that probably needs fixed in chrome, however.

Let me know how these packages work - download them all to a folder, then in that folder run `sudo dpkg -i *.deb` (if you're on mint or ubuntu).  The update manager (and apt-get upgrade) will want to replace these with the original (Mint repo-provided) packages, so skip these updates for now until a newer version is released, or just keep re-installing these after you do an update.

**Comment by bra1n** [comment]
@mtwebster I just tested your .deb packages and they fixed the problem for me. Thanks a lot for looking into this issue!

**Comment by bra1n** [comment]
Ok, I take it back. It fixed it for a short moment, then Chromium froze my system again and now Cinnamon refuses to boot in regular mode. :[ (always get fallback mode)

**Comment by mtwebster** [comment]
Hmm that looks a version issue between Cinnamon and Muffin now, unrelated to this bug.

Do me a favor, run:

`dpkg --list | grep muffin`

then

`dpkg --list | grep cinnamon`

and pastebin the results.

Then, you should be able to let mintupdate run, and it should reinstall a stable environment again for you, until I figure out what went wrong.

Are you in Mint or Ubuntu?

**Comment by mtwebster** [comment]
Actually, looking at what you posted above, once you get a stable system again, re-install everything but the -dbg package - it's not necessary, and I didn't provide you with one of its dependencies.

I'll remove the package from the preceding post.

**Comment by bra1n** [comment]
http://pastebin.com/raw/t0Y383sS
mintupdate doesn't show any new packages.
Okay, I fixed it by purging both muffin and cinnamon and reinstalling them. I lost all my cinnamon settings in the process, but at least I can use my desktop again.

**Comment by mtwebster** [comment]
Ack I didn't realize you're only running 2.2 there - these packages were for 2.8 (I just assumed you'd be running the latest release, sorry)

**Comment by entr** [comment]
Those muffin pkgs fixed it for me.

**Comment by rpbaptist** [comment]
Are these packages compatible with Cinnamon 2.8.6? I see 2.8.4 is referred in the filename.

**Comment by mtwebster** [comment]
Yes - muffin and cinnamon need only match Major.Minor versions generally, they don't have to be exact.

**Comment by rpbaptist** [comment]
I can confirm this solves the issue.

**Comment by mtwebster** [comment]
This fix is in the romeo repositories (along with lots of other fixes) - they can be enabled via Mint Sources. If all goes well, they'll be rolled out as normal updates within a week or so.

**Comment by entr** [comment]
Nice, thanks a ton.

**Comment by ipxwork** [comment]
hi,
now cinnamon not crash, but now move DOM nodes in chrome dev tools not work, is like a image and nodes move not work

**Comment by Draccoz** [comment]
Anybody knows anything about that thing happening to GNOME Shell? I know it is not the place for it, but I cannot find the fix for that issue for GNOME :(.

**Comment by mtwebster** [comment]
You could try opening a bug on their tracker - https://bugzilla.gnome.org/ or see if one exists already.

As I said above, though, I'm fairly certain this is a chrome issue, *not* directly related to what desktop you're using.  I'm not sure how willing they'd be to look into or implement some workaround/safety like we did.

**Comment by Draccoz** [comment]
It might be Chrome/Chromium issue, though it doesn't happen on Unity desktop (at least in virtual machine), so am not sure about it. There is a ticket on Gnomes' bugzilla, bumped it up a bit (thanks for the hint :) ). I've also reported that issue through Chromes' feedback system.
Cheers!

**Comment by mtwebster** [comment]
Updated packages released to main today.

@Draccoz it likely doesn't happen in Unity (or mate or maybe others) because of the different ways they interface with the hardware graphics layer, but no client should ever request a texture that is 20,000 pixels wide (see my comments above), thus I'm pretty certain this is a chrome issue.

**Comment by NamPNQ** [comment]
It affected with Ubuntu Gnome :(

**Comment by svlada** [comment]
@NamPNQ @mtwebster I'm experiencing similar problems on Unity as well. System logs out on dom reposition and Chrome crashes.

**Comment by BabbaFresh** [comment]
Still valid:

[marco@arc7 ~]$ cat /etc/*release
NAME="Arch Linux"
ID=arch
PRETTY_NAME="Arch Linux"
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

[marco@arc7 ~]$ chromium --version
Chromium 49.0.2623.112 

[marco@arc7 ~]$ google-chrome-stable --version
Google Chrome 49.0.2623.87

[marco@arc7 ~]$ gnome-shell --version
GNOME Shell 3.20.1

Both **Chrome** and **Chromium* crash on moving a DOM node in the Dev Tools Inspector. :cry:

**Comment by JosephMcc** [comment]
@BabbaFresh it's fixed in cinnamon. We can't do anything about fixing in chrome or gnome-shell.

**Comment by jasperprins** [comment]
+ 1

**Comment by GameCharmer** [comment]
+1
This has been happening for months and is still an issue when using the chrome inspector.  Running Ubuntu 15.10 & gnome-shell 3.16.4

$  cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"

$ google-chrome-stable --version
Google Chrome 49.0.2623.87 

gnome-shell --version
GNOME Shell 3.16.4

**Comment by pierrre** [comment]
@GameCharmer this issue is close.
Please read https://github.com/linuxmint/Cinnamon/issues/4789#issuecomment-210365867

**Comment by GameCharmer** [comment]
@pierrre realized this was for cinnamon in particular, so re-edited that post before you got that one in. :tongue:

**Comment by postbud** [comment]
after manipulation with DOM, bug return
GNOME Version 3.14.2
Chrome Version 51.0.2704.63 (64-bit)
CentOS 7

**Comment by mtwebster** [comment]
Please report Gnome-Shell issues to their bug tracker.
