### ISSUE TITLE
In Startup Applications, the startup delay is reset to 0

### ISSUE THREAD

**Issue by el-Salmon** [linuxmint/Cinnamon#4847]
In *Startup Applications*, the startup delay is reset to 0 after you edit a Startup Program with a delay and session is restarted. See #4396. 

Checked with cinnamon-control-center 2.6.0

**Comment by JosephMcc** [comment]
I just tested this on Cinnamon 2.8.4 and couldn't reproduce this. Would you mind retrying this after you update?

**Comment by mtwebster** [comment]
What program are you trying to change this on?  I've noticed some programs undo any changes you make here.  I think dropbox does, for instance.

**Comment by JosephMcc** [comment]
@mtwebster yeah, it seems dropbox always changes this back to 0. Other things I tried like mintUpdate, Indicator-LockKeys, mintWelcome all seem fine.

The dropbox icon in the systray does seem to work fine in 2.8 without the delay though.

**Comment by el-Salmon** [comment]
Yes, the application I want to delay is Dropbox.

**Comment by el-Salmon** [comment]
The issue is solved with Cinnamon 2.8. I can delay the dropbox start to show the icon in the systray now.

**Comment by RohanSJ** [comment]
Dropbox is still resetting the startup delay to 0, always. Whether you need a startup delay or not depends on your particular circumstances. I didn't have the missing-Dropbox-icon problem initially on Cinnamon 2.8 but I do now; the problem likely began when I updated or upgraded some other software. There may be a race condition that causes the problem to either appear or disappear when other installed software changes.

**Comment by Piiit** [comment]
@JosephMcc This issue still exists with Cinnamon 3.0.7. It works around 50% of the time, I guess that the race-condition explained by @RohanSJ still exists. Please reopen it.

Dropbox and I think also other applications have an option to set the "start on login" parameter (link?, configfile?), but I guess that it does not set the delay option (which is, I think, Cinnamon-specific and not standard). 

A solution could be to store Cinnamon-specific parameters separately, and copy them back into an overwritten autostart config file.

**Comment by Odyseus** [comment]
Hello, everybody.

I don't thing that this is a problem with Cinnamon. The problem is Dropbox that changes the **~/.config/autostart/dropbox.desktop** file every time Dropbox is started with the option **Start Dropbox on system startup**. If that option is unchecked, the **~/.config/autostart/dropbox.desktop** file is removed. In short, you may never be able to customize that file while that option is checked.

One way of working around this annoyance is to just uncheck the **Start Dropbox on system startup** option on Dropbox preferences and create a new startup entry like this:

![screenshot from 2016-09-16 06-37-36](https://cloud.githubusercontent.com/assets/3822556/18581703/1fc523fc-7bd8-11e6-8391-4cb51da88adb.png)

This also happens on KDE. To fix the problem of the systray icon for Dropbox disappearing, I wanted to change the **Exec** line on the .desktop file (by adding dbus-launch to the command). But every time Dropbox started, it changed the **~/.config/autostart/dropbox.desktop**.

**Comment by mainmachine** [comment]
So this is a problem with Dropbox, basically? 

Looks like lazy programming - they're just recreating dropbox.desktop on launch every time...?

**Comment by Odyseus** [comment]
Hello, @mainmachine.

> So this is a problem with Dropbox, basically?

I only observed this behaviour with Dropbox. Maybe other applications with options to start at startup do the same. I don't really know.

> they're just recreating dropbox.desktop on launch every time...?

That's right. And it's easily reproducible.

- Just check the option **Start Dropbox on system startup** on Dropbox preferences and close Dropbox.
- Now open with a text editor the **~/.config/autostart/dropbox.desktop** file and do any edits to it and save.
- Start Dropbox and see how all the changes to the **~/.config/autostart/dropbox.desktop** file are reverted.

**Comment by mainmachine** [comment]
@Odyseus 

>    > So this is a problem with Dropbox, basically?
> 
> I only observed this behaviour with Dropbox. Maybe other applications with options to start at startup do the same. I don't really know.

Yes, I just meant that the problem (and thus the solution) is on the application side, not on the O/S side. It's likely there are other applications that would do this too - it's easy to be heavy-handed, sophistication takes a bit more effort...

Someone should raise a bug with Dropbox...

**Comment by simonwiles** [comment]
Best solution for this, imo, is to make the changes you need (either by hand in the .desktop file, or using Cinnamon's "Startup Applications" panel), and then, before the next time Dropbox starts, make the `dropbox.desktop` file read-only.  This will prevent Dropbox clobbering it on startup (it will fail silently and move on).  e.g.:

    chmod a-w ~/.config/autostart/dropbox.desktop
