### ISSUE TITLE
Panel disappears from time to time on resume

### ISSUE THREAD

**Issue by A-Shahbazi** [linuxmint/Cinnamon#4891]
It seems sometimes on wakeup from suspend or hibernate gnome-screensaver gets run and it causes panel to hide. User should logout and relogin to fix it(even a cinnamon --replace won't help)
Here's the screenshot of what happens:
![screenshot from 2015-11-29 17 59 35](https://cloud.githubusercontent.com/assets/7456141/11457644/9807e23c-96c3-11e5-9539-4b22c7c475f6.png)

**Comment by sudoer** [comment]
I'm having the same problem on Ubuntu 15.10 with cinnamon-desktop installed.

**Comment by A-Shahbazi** [comment]
Removing "gnome-screensaver" solved the issue for me but the desktops which use gnome-screensaver (for locking screen say) can't use it anymore.

**Comment by mtwebster** [comment]
Fixed by 98e3036d15ebfdda73264c04044e69e4d53c542c, b6cc07337f1ab2913610735b977c470d4c05085f

**Comment by talonx** [comment]
This still happens for me on Ubuntu 16.04, 4.4.0-22, Cinnamon 2.8.6
