### ISSUE TITLE
Window (Java app) not shown on the panel

### ISSUE THREAD

**Issue by f2404** [linuxmint/Cinnamon#5217]
One window is not shown among others on the panel - it's a Java app (game client). It's there in the Alt-Tab switching window.
Cinnamon 2.8.8, Arch Linux.

The same client window is shown fine in my other DE - LxQt.

**Comment by f2404** [comment]
I think the following lines appear in `.xsession-errors` when the window disappears from the panel:
```
(cinnamon:20517): Cjs-WARNING **: JS ERROR: Error: Argument 'text' (type utf8) may not be null
WindowPreview.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:108
WindowPreview@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:77
AppMenuButton.prototype.onPreviewChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:288
AppMenuButton.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:255
AppMenuButton@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:207
MyApplet.prototype._addWindow@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1056
MyApplet.prototype._onWindowAdded@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:921


(cinnamon:20517): Cjs-WARNING **: JS ERROR: Error: Argument 'text' (type utf8) may not be null
WindowPreview.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:108
WindowPreview@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:77
AppMenuButton.prototype.onPreviewChanged@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:288
AppMenuButton.prototype._init@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:255
AppMenuButton@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:207
MyApplet.prototype._addWindow@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:1056
MyApplet.prototype._onWindowAdded@/usr/share/cinnamon/applets/window-list@cinnamon.org/applet.js:921
```

**Comment by JosephMcc** [comment]
Right click the window list and choose "Configure the window list". In the window that pops up uncheck "Show window thumbnails on hover". If that fixes the issue, this has already been fixed in git master. You may need to restart Cinnamon for it to work.

**Comment by f2404** [comment]
This seems to fix the issue, thanks!

Does this mean that the git master version is able to show thumbnails for the windows that allow that, and still show the window list elements for the windows that do not provide thumbnails? I would like it to behave this way.

**Comment by JosephMcc** [comment]
It should all work properly now. You should get the item in the window list plus a proper window preview for it.
Closing this since it should already be fixed for 3.0
