### ISSUE TITLE
[3.0.1] Cinnamon freezes with wine programs and when changing UI themes

### ISSUE THREAD

**Issue by acidicX** [linuxmint/Cinnamon#5254]
Cinnamon 3.0.1 freezes when a wine program is started or when the symbol / UI theme is changed in `cinnamon-settings`.

The `cinnamon --replace` process uses 100% CPU load on one core and will not restart itself. I need to kill (sighup is enough) it and restart lightdm.

System:
Arch x64
lightdm
xf86-video-intel (w/ virtualGL)

Nothing to be found in Xorg logs or glass.log, anywhere else I could look?

**Comment by pconiglio** [comment]
i'm having the exact same problem since upgrading to cinnamon 3.0.1 yesterday, when running wine program or when trying to reload cinnamon with alt+f2 r, the desktop freezes and when i check the procceses, cinnamon --replace is eating 100% cpu on one core and will not restart itself. i also run under Arch x64 but with nvidia drivers, nothing on the journalctl or xorg logs either.

**Comment by acidicX** [comment]
Note: I'm also running with nvidia drivers (optimus laptop), but the DE runs with intel only afaik.

**Comment by Lukypie** [comment]
I'm running Arch without an nvidia card but sometimes I get random freezes, Idk if these are releated. 
Also on the intel GPU notebook I'm getting this.

**Comment by MatthewNewland** [comment]
I also am getting freezes (Arch x64, open source Radeon drivers). I haven't found any particular pattern to it (I can change the UI theme just fine without it freezing, and wine programs seem OK).

**Comment by Lukypie** [comment]
I tried checking the .xsession_errors and there are a lot of them

**Comment by pconiglio** [comment]
the freezes seem random, sometimes it works ok but most times it hangs :/

**Comment by MatthewNewland** [comment]
OK. I actually can confirm that this happens consistently when I change _Cinnamon_ themes (not GTK themes).

Looking through .xsession-errors, I see an error message that starts:

`Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0`

before each crash (got it by tailing .xsession-errors in a TTY).

Nothing good, so far as I can tell, in glass.log (just the usual applet-loading messages).

**Comment by MatthewNewland** [comment]
Are we all using lightdm? When I start Cinnamon from a TTY, this issue doesn't seem to occur.

Tomorrow, I guess I'll look into alternative display managers.

**Comment by Lukypie** [comment]
Tried in a tty, but also here random hangs occurs.

**Comment by MatthewNewland** [comment]
In case it helps: [here](https://gist.github.com/MatthewNewland/3411e58b2cec3ea2d138007590f91386) is the GDB backtrace I get.

**Comment by leigh123linux** [comment]
@MatthewNewland It isn't a help because you haven't got the required debug packages installed.

**Comment by MatthewNewland** [comment]
Sorry; Arch Linux doesn't have precompiled debug packages.

Now that I've built them, I've updated the gist [here](https://gist.github.com/MatthewNewland/3411e58b2cec3ea2d138007590f91386); hopefully it's more helpful.

**Comment by MatthewNewland** [comment]
OK. As strange as this sounds, I think this may be related to gnome-terminal (version 3.20.1 from the Arch repositories).

To reproduce:

1. Start Cinnamon
2. Open the Themes app and change any of the themes, or open a Wine program, and observe that Cinnamon does not freeze
3. Open the gnome-terminal app.
4. Open the Themes app and change any of the themes, or open a Wine program, and observe that Cinnamon _does_ freeze.

Also, Cinnamon still freezes happens even after I close the gnome-terminal app; it's as if opening it puts the desktop into a bad state. It requires a restart of Cinnamon to get it back into a good state.

I know it sounds a bit weird, but I followed the procedure above about ten times, and that was what I saw each time. In the meantime, I've switched to a different terminal emulator (terminator), and am not experiencing freezes.

@acidicX and @pconiglio, can you reproduce, or is it just me?

**Comment by acidicX** [comment]
I've also noticed that it is worse with gnome-terminal open, I'll try to confirm it today.

**Comment by leigh123linux** [comment]
I'm also see issues when running updates from gnome-terminal.

**Comment by acidicX** [comment]
I did not have a crash today with a lot of usage (dual screen usage as well). Seems to be an issue with gnome-terminal and cinnamon.

**Comment by leigh123linux** [comment]
It seem installing any gui app that runs gtk-update-icon-cache crashes cinnamon

**Comment by MatthewNewland** [comment]
Just for the record, this problem occurs in software rendering mode too.

**Comment by brownsr** [comment]
the symptoms sound like an infinite loop.  Lestcape and I found one in the indicator manager code when doing our respective PRs.  I've just pushed a fix.  Maybe completely unrelated of course, but worth trying if the programs you are using make use of indicators. https://github.com/linuxmint/Cinnamon/pull/5275

**Comment by MatthewNewland** [comment]
@brownsr I still get the freeze after applying your patch. Thanks, though. And I'll try and look for any infinite loops when I finally get around to trying to debug it in more depth.

**Comment by MatthewNewland** [comment]
@brownsr You were right. This is an infinite loop in some Muffin code; the for-loop in update_style_contexts() defined in src/ui/frames.c is going forever (I just added a counter variable, and it got up to at least 20000 times, which seems a bit ridiculous). I think I'll open a bug on the muffin repository.

For now, I've simply patched Muffin to not allow that loop to go more than 10 times (there's a patch below if anyone is interested, against version 3.0.0 of Muffin). I don't know _why_ the loop is going forever; perhaps a GLib or GTK change? Anyway, the freeze is no longer happening for me, at least not the gnome-terminal related one.

```
From 23838329f849bbe406cf0aed9e8d3d5437d2c998 Mon Sep 17 00:00:00 2001
From: Matthew Newland <email-removed@example.com>
Date: Thu, 5 May 2016 16:56:01 -0700
Subject: [PATCH] Stop update_style_contexts() after 10 loops

---
 src/ui/frames.c | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/src/ui/frames.c b/src/ui/frames.c
index 9afbde5..e9edf3b 100644
--- a/src/ui/frames.c
+++ b/src/ui/frames.c
@@ -235,13 +235,15 @@ update_style_contexts (MetaFrames *frames)
 {
   GtkStyleContext *style;
   GList *variants, *variant;
+  // Temporarily keep it from going crazy with the variants
+  int loops = 0;
 
   if (frames->normal_style)
     g_object_unref (frames->normal_style);
   frames->normal_style = create_style_context (frames, NULL);
 
   variants = g_hash_table_get_keys (frames->style_variants);
-  for (variant = variants; variant; variant = variants->next)
+  for (variant = variants; variant && (loops < 10); variant = variants->next, loops++)
     {
       style = create_style_context (frames, (char *)variant->data);
       g_hash_table_insert (frames->style_variants,
-- 
2.8.2
```

**Comment by mtwebster** [comment]
Can you try this patch? https://github.com/linuxmint/muffin/commit/6120bddefd709d3f1611aa2af706fb3c43b5ae22

It's already in git master as well.

**Comment by MatthewNewland** [comment]
@mtwebster It works! Thanks so much. I'll close the bug on the muffin repository.

**Comment by pconiglio** [comment]
how are you aplying this patch? i want to try it too, thanks.

**Comment by MatthewNewland** [comment]
@pconiglio You're on Arch, right? I created a gist [here](https://gist.github.com/MatthewNewland/0b83b5db44a38bf64fbceda182bbeb2b) with all the files you should need to build it. Just download them all/clone the gist and run `makepkg -sri` from the directory the files were downloaded into.

**Comment by pconiglio** [comment]
thanks @MatthewNewland, i updated arch and the issue seems fixed, no more freezes!

**Comment by acidicX** [comment]
Seems to be fixed. I did not have any crashes today, I'll close the issue in a few days when everything stays fine. Thanks for the quick fix!

**Comment by brownsr** [comment]
Hi @acidicX  are you ready to close this yet ?
