### ISSUE TITLE
Window border bug when close to dektop border 

### ISSUE THREAD

**Issue by ManuelSchneid3r** [linuxmint/Cinnamon#5292]
I cant really say how to reproduce this but when I move windows to the border of the screen and over it there happen strange things with the righ window border. A few screenies:

![bildschirmfoto vom 2016-05-12 18-56-28](https://cloud.githubusercontent.com/assets/3252315/15223258/c3476e9a-1873-11e6-90c4-830b5b2c6fe5.png)
![bildschirmfoto vom 2016-05-12 18-57-26](https://cloud.githubusercontent.com/assets/3252315/15223257/c3438b68-1873-11e6-9f49-b1829f2285b4.png)

Edit: Environment is archlinux. So latest releases of software.

**Comment by JosephMcc** [comment]
Does it happen with windows besides nemo?

**Comment by ManuelSchneid3r** [comment]
How do you mean? I found out that the problem most often appears when I manually maximise the window. And then move it.

**Comment by JosephMcc** [comment]
I mean does it happen when using say terminal or some other application besides nemo. The second bit of info you provided is also helpful "the problem most often occurs when...". Please gives as much of this info as you can when opening an issue. If a bug cannot be reproduced it's almost impossible to figure out what's going on and how to fix it.

**Comment by JosephMcc** [comment]
This looks like the same issue as https://github.com/linuxmint/Cinnamon/issues/5363
Is it happening when the window is slightly large than the screen?

**Comment by ManuelSchneid3r** [comment]
> Is it happening when the window is slightly large than the screen?

Yes. Well yes #5363 looks like a dup.

**Comment by JosephMcc** [comment]
Should be fixed on master by https://github.com/linuxmint/muffin/pull/245#event-689827357

**Comment by ManuelSchneid3r** [comment]
cinnamon 3.0.5-1
![image](https://cloud.githubusercontent.com/assets/3252315/16194786/a9da2050-36f6-11e6-84aa-d86415add945.png)
Not fixed. Ignore this if d8dc04f is not in 3.0.5.

**Comment by JosephMcc** [comment]
Muffin is still at 3.0.4. When it gets tagged at 3.0.5 it should have the fix.
