### ISSUE TITLE
No action to select when battery is criticaly low

### ISSUE THREAD

**Issue by jeroenst** [linuxmint/cinnamon#7437]
```
Cinnamon 3.6.7
Linux Mint 18.3 Sylvia
VGA compatible controller: Intel Corporation Device 5916 (rev 02)
64Bit
 ```

**Issue**
It is not possible to select an action when battery level is critical

**Steps to reproduce**
Open the power settings at the battery icon on the lower panel, click on the drop down box When battery is critically low, there are no other options then do nothing

**Expected behaviour**
Able to select turn off, hibernate or sleep.

**Other information**

**Comment by icarter09** [comment]
We believe this issue is fixed. Please test against the latest Cinnamon version (4.2). 

If the issue happens again, create a new issue and add the output of "cinnamon-settings sound".

**Comment by smurphos** [comment]
Hi @icarter09, this still sort of an issue for Mint users, in the default value in dconf for this setting is hibernate, but hibernate is disabled by default on Mint so out of the box the GUI setting is empty. Suspend isn't offered as an option. The latter restriction is hard coded into the cs_power modules is.

**Comment by jeroenst** [comment]
The only options now available are "Do Nothing" or "Shutdown immediately".

Still missing the options hibernate and sleep.

**Comment by smurphos** [comment]
@jeroenst - you might find this tutorial on the Mint forums helpful - https://forums.linuxmint.com/viewtopic.php?f=42&t=302573

**Comment by jeroenst** [comment]
Thanx for the tutorial, but imo al options should be available out of the box without extra user interaction.
