### ISSUE TITLE
"Configure" option for menu applet in panel not working

### ISSUE THREAD

**Issue by UncleSpellbinder** [linuxmint/cinnamon#8801]
* Cinnamon version 4.2.3
* Arch Linux, 64 bit
* Kernel 5.2.9-arch1-1-ARCH
* CPU: AMD A10-7800 Radeon R7 4C+8G (4) @ 3.500GHz
* GPU: AMD ATI Radeon R7 Graphics

**Issue**
Clicking "configure" no longer works, nothing happens. The "About" and "Remove Menu" options both work, as the dialog boxes are shown after clicking those. When I click "configure", nothing happens. All other applets in the panel that have a "configure " option work as expected.

**Steps to reproduce**
Right click menu applet, select "configure".

**Expected behaviour**
Configure dialog box should appear.

**Other information**
I tried with two other menu applets (Cinnamenu and CinnVIIStarkMenu). Same issue with both of those as well, "About" and "Remove Menu" both work as the dialog boxes are shown after clicking those. When I click "configure", nothing happens.

**Comment by JosephMcc** [comment]
Do your logs or .xsession-errors show anything that might be related? I can't reproduce the issue here on Mint 19.2.

**Comment by UncleSpellbinder** [comment]
I can copy/paste here. It's quite long. I couldn't sus anything out.

**Comment by JosephMcc** [comment]
Please do or put it in pastebin or something. Thanks

**Comment by UncleSpellbinder** [comment]
Here's the Pastebin link: [https://pastebin.com/TNbMu7Qq](url)

**Comment by JosephMcc** [comment]
Thanks. Nothing stands out for me in there. Maybe someone else will see something.

**Comment by JosephMcc** [comment]
Could you try running `xlet-settings applet menu@cinnamon.org` with the stock menu in the panel. This should show it's settings or give you an error of some kind.

**Comment by UncleSpellbinder** [comment]
[daveb@archlinux ~]$ xlet-settings applet menu@cinnamon.org
Segmentation fault (core dumped)
[daveb@archlinux ~]$

**Comment by UncleSpellbinder** [comment]
Using sudo, there is more info...

```
[daveb@archlinux ~]$ sudo xlet-settings applet menu@cinnamon.org
[sudo] password for daveb: 
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 554, in <module>
    window = MainWindow(xlet_type, *sys.argv[2:])
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 144, in __init__
    self.load_instances()
  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 260, in load_instances
    dir_items = sorted(os.listdir(path))
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cinnamon/configs/menu@cinnamon.org'
[daveb@archlinux ~]$ 
```

**Comment by mtwebster** [comment]
are there any entries in the "System Reports" app (in the menu) or run 'mintreport`.  Look under "Crash reports"

**Comment by claudiux** [comment]
@UncleSpellbinder Do not use sudo. The root user does not use this applet.

**Comment by claudiux** [comment]
@UncleSpellbinder Can you try: `cinnamon-settings applets menu@cinnamon.org`?

**Comment by UncleSpellbinder** [comment]
```
[daveb@archlinux ~]$ cinnamon-settings applets menu@cinnamon.org
Segmentation fault (core dumped)
[daveb@archlinux ~]$
```

**Comment by UncleSpellbinder** [comment]
mtwebster, there is no "System Reports" app. I suspect running "mintreport" will not help, I'm running Arch.

**Comment by mtwebster** [comment]
oh sorry I didn't pay attention to original post :)

You'll have to debug it - this link should help:

https://github.com/linuxmint/Cinnamon/wiki/How-to-use-GDB-to-gather-debug-information-on-a-program

**Comment by smurphos** [comment]
What icon theme do you have set. I ask as a Mint user reported a similar issue on the forums and it appears the Yaru++ icon theme was a factor.

https://forums.linuxmint.com/viewtopic.php?f=90&t=299968

**Comment by UncleSpellbinder** [comment]
> What icon theme do you have set. I ask as a Mint user reported a similar issue on the forums and it appears the Yaru++ icon theme was a factor.
> 
> https://forums.linuxmint.com/viewtopic.php?f=90&t=299968

WOW. You are correct! I was using the Korla icon theme. Switched to Arc. "Configure" works as expected. 

I'm so sorry to have wasted everyone's time.

Thanks for the info, smurphos!

**Comment by UncleSpellbinder** [comment]
**SOLVED**

**Comment by smurphos** [comment]
It's not a waste of time. It may be an icon theme related bug, but it should not make the settings module crash if it is.

The Yaru++ theme is from https://github.com/Bonandry/yaru-plus

I got as far as reproducing the crash with the Yaru++ theme on Mint, but haven't investigated any furhter

**Comment by JosephMcc** [comment]
This should be fixed by: https://github.com/linuxmint/xapps/commit/b325768013de6c42f743df58415be24c8e94ed87

**Comment by eli-schwartz** [comment]
@UncleSpellbinder I'm uploading the new xapps version to Arch's community repository as we speak, so your original icon theme should work now I guess.

`pacman -Syu 'xapps>=1.4.9-1'`

**Comment by smurphos** [comment]
> This should be fixed by: [linuxmint/xapps@b325768](https://github.com/linuxmint/xapps/commit/b325768013de6c42f743df58415be24c8e94ed87)

Partially fixed - you still can't open the icon picker GUI from the configure GUI with one of the problematic icon themes. 

cinnamon-desktop-editor is also broken by these icon themes

```
steve@steve-Inspiron-5580:~$ cinnamon-desktop-editor -m nemo-launcher -d ~/Desktop

Segmentation fault (core dumped)
```

**Comment by mtwebster** [comment]
There's nothing we can do with this other than isolating it as much as possible, which that patch did, this is a gtk issue.

https://gitlab.gnome.org/GNOME/gtk/issues/2111

**Comment by smurphos** [comment]
Thanks @mtwebster - I'm not sure if it's relevant for your upstream bug report, but fixing the typo in the index that produces the warning doesn't eliminate the seg-fault.

**Comment by UncleSpellbinder** [comment]
> @UncleSpellbinder I'm uploading the new xapps version to Arch's community repository as we speak, so your original icon theme should work now I guess.
> 
> `pacman -Syu 'xapps>=1.4.9-1'`

Thanks. As was mentioned, it's partially fixed as I can't open the icon picker GUI from the configure GUI. But, some progress is better than none. Much appreciated.

**Comment by gusbemacbe** [comment]
Hi @smurphos !

I am co-author of Yaru++. It had "no size field", because the author of icons theme used the old version of Suru++ Ubuntu, which caused bugs in the Yaru++ theme.

During a month, I have worked, fixed and upgraded the whole Yaru++. I have already told him not to copy or use the old version of Suru++ Ubuntu for his new icons themes. 

I have just released the new version today. You can check and test.

**Comment by Davetheraveuk** [comment]
Hi, I am having the same problem as OP.
Here is my terminal output:

`[dave@RebornOS Desktop]$ cinnamon-settings applets menu@cinnamon.org
Traceback (most recent call last):

  File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 17, in <module>
    from JsonSettingsWidgets import *

  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 332, in <module>
    globals()["JSONSettings"+widget] = json_settings_factory(widget)

  File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 313, in json_settings_factory class NewClass(globals()[subclass], JSONSettingsBackend):

KeyError: 'SoundFileChooser'`

Dunno what is causing this.
Let me now if you require any more info.
Dave.

**Comment by pawanneupane** [comment]
> Hi, I am having the same problem as OP.
> Here is my terminal output:
> 
> ```
> 
> [dave@RebornOS Desktop]$ cinnamon-settings applets menu@cinnamon.org
> Traceback (most recent call last):
> 
>   File "/usr/share/cinnamon/cinnamon-settings/xlet-settings.py", line 17, in <module>
>     from JsonSettingsWidgets import *
> 
>   File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 332, in <module>
>     globals()["JSONSettings"+widget] = json_settings_factory(widget)
> 
>   File "/usr/share/cinnamon/cinnamon-settings/bin/JsonSettingsWidgets.py", line 313, in json_settings_factory class NewClass(globals()[subclass], JSONSettingsBackend):
> 
> KeyError: 'SoundFileChooser'
> ```
> 
> Dunno what is causing this.
> Let me now if you require any more info.
> Dave.

I'd been facing the same issue for the past couple of days. The latest cinnamon update seems to have fixed it.

**Comment by leigh123linux** [comment]
@pawanneupane @Davetheraveuk 

https://github.com/linuxmint/cinnamon/issues/9305

**Comment by pawanneupane** [comment]
@leigh123linux Thanks. Updated Cinnamon and everything's working fine again. Cheers!

**Comment by Davetheraveuk** [comment]
@pawanneupane @leigh123linux
Yup. Can confirm, all is good.
Thanks guys.
Dave.
