### ISSUE TITLE
Lockscreen issue after suspending laptop by closing the screen.

### ISSUE THREAD

**Issue by panks103** [linuxmint/cinnamon#9414]
```
 * Cinnamon version : 4.6.6
   - Using LinuxMint 20 Cinnamon stable
 * Distribution - LinuxMint 20
 * onboard Intel UHD 620 graphics
 * 64 bit
 ```

**Issue**
Lock Screen not being displayed correctly after resuming laptop from suspend.

**Steps to reproduce**
I ususally suspend my laptop by closing the screen and then resume work later by open the lid. In LM 20 cinnamon after opening the screen/ resuming from suspend the lock screen is not displayed instead the desktop is visible without entering a password. However nothing responds, mouse works as I can see the cursor moving, however clicking on any icons doesn't work. Then if I press the power button the tinted lock screen appears with option to enter the password. This behaviour is not intuitive as it appears that the laptop is frozen. As a work around I have added a message to be displayed on the lock screen which then forces the lock screen to appear. However even enabling this the lock screen doesn't show password field until I press power button. This was not an issue in LM 19.3 and earlier.

**Expected behaviour**
As soon as laptop screen is opened it should resume from suspend and display the lock screen for entering password.

**Other information**

**Configuration info, if applicable**

```

Please paste here

```

**Comment by nightelf7** [comment]
It happens to me too.

**Comment by mrtree4** [comment]
I have the same issue.
OS: Arch Linux x86_64 
Kernel: 5.7.6-arch1-1
CPU: Intel m3-7Y30 (4) @ 2.600GHz 
GPU: Intel HD Graphics 615

**Comment by HenryJk** [comment]
I have similar issue.
OS: Arch Linux
Kernel: 5.7.6-arch1-1
CPU: Intel© Core™ i7-9750H CPU @ 2.60GHz × 6
GPU: Intel Corporation UHD Graphics 630 (Mobile)

On wakeup after suspend, the lockscreen appear, I can enter password and get into cinnamon session. However, cinnamon can't be interacted with. I can't click anything, nothing works, although it still somehow animating/displaying my desktop. This doesn't always happen but it's almost always happen if I leave it on suspend overnight. Attached is my .xsession-errors file
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4861614/xsession-errors.txt)

**Comment by HenryJk** [comment]
Another occurence, but the lockscreen doesn't even appear. Just directly to a desktop that can't be interacted with. 
[xsession-errors.txt](https://github.com/linuxmint/cinnamon/files/4873059/xsession-errors.txt)

**Comment by kameshkotwani** [comment]
## Password Input not showing up
The lock screen issue is happening with me too. As soon as I open my Laptop's lid, it turns on, but menu to enter password doesn't appears, I simply type my password and press enter and I can easily log-in. 
I have dual graphics, NVIDIA GT-840M and intel also. I primarily use the intel integrated graphics.
## As a work-around
Whenever you open the lid, and no password entry option is coming up, simply type in the password and press ENTER. It will log-in without any problems.

**Comment by puenka** [comment]
I can confirm the behaviour on my machine (incidentally the exact same setup as @panks103 on my ThinkPad L480) and also the workaround by blindly typing in the passphrase.
The issue does not occur when suspending from the menu. I only have mild security concerns because window content is not shown (or only briefly until the view jumps to the desktop).

**Comment by cadadr** [comment]
I've updated my installation and rebooted a few minutes ago, and it seems that this issue was fixed after that.

**Comment by panks103** [comment]
I haven't seen this issue lately, I guess some updates might have fixed this behaviour so I am closing this issue.

**Comment by cdeegz** [comment]
I believe this issue is not resolved as it is still occurring on at least my system. I also believe this is related to #9554 and cinnamon-screensaver (https://github.com/linuxmint/cinnamon-screensaver/issues/342).

For reference, I am using cinnamon 4.6.7-1 and cinnamon-screensaver 4.6.0-2
