### ISSUE TITLE
Network Manager Applet Does Not Show Wifi Networks Properly After Connecting To A Different Wifi Network

### ISSUE THREAD

**Issue by TechnologyMan101** [linuxmint/cinnamon#9564]
```
 * Cinnamon version - 4.6.7
 * Distribution - Linux Mint 20 Cinnamon
 * Graphics Card - Intel UHD Graphics 620 (built in kernel driver)
 * amd64 Intel Core i7-8550U
 ```

**Issue**
Selecting a different Wifi network causes the Network Manager applet to either make all connections disappear or make the current connection disappear visually. This happens on a fresh install too. I also took some old Mint 19 DVDs and installed it on my computer to see if that version has the problem too. That version also has the same problem. Restarting Cinnamon with `<Alt>F2` with command `r` followed by `<return>` temporarily fixes the problem until a different network is selected again.

**Steps to reproduce**
1. Make sure you are already connected to a Wifi network.
2. Select a different network, either from the Network Manager applet or from the settings panel.
3. Open the Network Manager applet and see what happens.
4. The current network is not shown, all other networks are not shown, or all networks are not shown.

**Expected behaviour**
All networks should be shown even if the network connection has changed.

**Other Information**
![image](https://user-images.githubusercontent.com/65311278/92414313-8a448480-f108-11ea-8da1-c857a9c13954.png)
Where is my current network in the Network Manager applet?????

**Comment by TechnologyMan101** [comment]
![image](https://user-images.githubusercontent.com/65311278/92829925-a0ad4300-f389-11ea-8fb5-ce3a943fa5a0.png)
Here is another screenshot. Most of the available networks are gone. This was after I had to reconnect because I accidentally turned off the router.

**Comment by TechnologyMan101** [comment]
![image](https://user-images.githubusercontent.com/65311278/93171472-04af6e80-f6de-11ea-83ec-4f77843cafec.png)
Another screenshot, again. This time, all networks are gone and also leaves a sizable gap.

**Comment by icarter09** [comment]
@TechnologyMan101 can you test out that PR whenever you have a moment? I did several rounds of testing (connecting to diff networks and toggling the wifi on/off) and believe that should fix the issue. If it doesn't fix the issue, just let me know. Thanks.

**Comment by TechnologyMan101** [comment]
Yep, I can test this tonight.

**Comment by mtwebster** [comment]
Wait I thought this is fixed already in git master?

**Comment by TechnologyMan101** [comment]
I looked at that commit that was supposed to fix it but it still happens. And since both of my computers are up-to-date and have the same problem, that commit might not have solved everything.

**Comment by mtwebster** [comment]
It's not in a release yet, you'd have to apply the patch to applet.js yourself (unless you're using the nightly PPA for cinnamon, in which case it would indeed seem this wasn't fixed).

**Comment by TechnologyMan101** [comment]
Do you have any idea when it will be released, or will it be released along with Mint 20.1?

**Comment by icarter09** [comment]
Verified this is working correctly with patch `42960e3`.

**Comment by TechnologyMan101** [comment]
Do you have any idea when this is going to reach Linux Mint?

**Comment by icarter09** [comment]
@TechnologyMan101 are you still experiencing this issue?

**Comment by TechnologyMan101** [comment]
> @TechnologyMan101 are you still experiencing this issue?

Um I don't have an installation at the moment because I recently got a new SSD. I can get an installation running tomorrow afternoon (about 15:00 PT)

**Comment by TechnologyMan101** [comment]
Sorry, been quite busy lately but I'll report in a day or two

**Comment by TechnologyMan101** [comment]
Okay just tested

It still does it. Also noticed that it happens when NOT already connected to a network

![PXL_20210526_024133150](https://user-images.githubusercontent.com/65311278/119594755-3dd1cf80-bd91-11eb-854b-1396710b41f1.jpg)

**Comment by TechnologyMan101** [comment]
Also want to note something. May be unrelated but not sure.

Virtual adapters like ones from tether apps like Easytether Pro don't show at all even in the panel. I don't expect it to show in settings (because all distros and even Windows does this) but I'd expect to see a connected icon like any other environment. My internet has been confirmed working even with that icon not working. When I unplug my USB cable, it does detect and show that something disconnected.
