### ISSUE TITLE
Incremental search should prioritize app titles and files matching the substring

### ISSUE THREAD

**Issue by dandv** [linuxmint/cinnamon#9790]
```
 * Cinnamon version 4.6.7
 * Distribution - Mint 20
 ```

**Issue**
Searching for "tra" in the Start menu shows up "Desktop" and "LibreOffice Base" before "**Tra**nsmission"

**Steps to reproduce**
1. Press Super
2. Type `tra`

**Expected behaviour**
"Transmission" should be at the top of the list.

![Incremental search should prioritize app titles](https://user-images.githubusercontent.com/33569/102987463-6c800d00-44b6-11eb-9d20-7fb82cb5087e.png)

**Comment by NikoKrause** [comment]
It's fixed in Cinnamon 4.8 / Mint 20.1

**Comment by dandv** [comment]
@NikoKrause: I've just updated to Mint 20.1, but I still see irrelevant results:

![image](https://user-images.githubusercontent.com/33569/104388502-5970c380-54dd-11eb-965b-6e6c1e3b08d9.png)

**Comment by NikoKrause** [comment]
What about your first example with "tra"?

**Comment by dandv** [comment]
`tra` works as intended.

**Comment by dandv** [comment]
Can we reopen this please?

**Comment by NikoKrause** [comment]
You are searching for a file. The search prefers apps before files. The found apps probably have "exp" in their descriptions

**Comment by dandv** [comment]
I see. IMO, a file is more specific than an app, so if a file matches *just as well as an app*, it should be returned instead. Even more so, if the name of the file is a substring match, but the match against the app is in the metadata, I believe the file should be favored. Another argument is the enhancement in 20.1 that allows favoriting files - this teaches users that files are more important now.

**Comment by NikoKrause** [comment]
This is a legit point.
Do you want to open a new issue for that or update this one here, to reflect the fact, that files should be matched just as well as apps, so I can reopen this issue?

**Comment by dandv** [comment]
Thanks, I've updated the issue title. Let me know if I need to update/add any reasoning.
